INSERT INTO `{site_prefix}option` VALUES('{ulid_1}', 'sitename', '{sitename}');
INSERT INTO `{site_prefix}option` VALUES('{ulid_2}', 'site_description', 'Just another Devflow site');
INSERT INTO `{site_prefix}option` VALUES('{ulid_3}', 'charset', 'UTF-8');
INSERT INTO `{site_prefix}option` VALUES('{ulid_4}', 'admin_email', '{admin_email}');
INSERT INTO `{site_prefix}option` VALUES('{ulid_5}', 'site_locale', 'en');
INSERT INTO `{site_prefix}option` VALUES('{ulid_6}', 'cookieexpire', '604800');
INSERT INTO `{site_prefix}option` VALUES('{ulid_7}', 'cookiepath', '/');
INSERT INTO `{site_prefix}option` VALUES('{ulid_8}', 'site_timezone', '{timezone}');
INSERT INTO `{site_prefix}option` VALUES('{ulid_9}', 'api_key', '{api_key}');
INSERT INTO `{site_prefix}option` VALUES('{ulid_10}', 'date_format', 'd F Y');
INSERT INTO `{site_prefix}option` VALUES('{ulid_11}', 'time_format', 'h:i A');
INSERT INTO `{site_prefix}option` VALUES('{ulid_12}', 'content_per_page', '6');
