<?php

use App\Application\Devflow;

use function App\Shared\Helpers\admin_url;
use function App\Shared\Helpers\get_auth_screen_logo;
use function Codefy\Framework\Helpers\trans_attr;
use function Codefy\Framework\Helpers\trans_html;

$this->parent('framework::backend/layouts/auth-layout');
$this->block('auth', function ($params) {
?>

    <div class="brand">
        <?=get_auth_screen_logo();?>
        <?=Devflow::$PHP->flash->display();?>
    </div>

    <div class="card fat">
        <div class="card-body">
            <form method="post" action="<?=$params['url'];?>" class="my-login-validation" novalidate="" autocomplete="off">
                <div class="form-group">
                    <label for="username"><?=trans_html('Username');?></label>
                    <input id="username" type="text" class="form-control" name="user_login" required="required" autofocus>
                    <div class="invalid-feedback">
                        <?=trans_html('Username is invalid.');?>
                    </div>
                </div>

                <div class="form-group">
                    <label for="password"><?=trans_html('Password');?>
                        <a href="<?=admin_url('reset-password/');?>" class="float-right">
                            <?=trans_html('Forgot Password?');?>
                        </a>
                    </label>
                    <input id="password" type="password" class="form-control" name="user_pass" required="required" data-eye>
                    <div class="invalid-feedback">
                        <?=trans_html('Password is required.');?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="custom-checkbox custom-control">
                        <input type="checkbox" name="rememberme" value="yes" id="remember" class="custom-control-input">
                        <label for="remember" class="custom-control-label"><?=trans_html('Remember Me');?></label>
                    </div>
                </div>

                <div class="form-group m-0">
                    <input type="submit" name="login-submit" class="btn btn-submit btn-block" value="<?=trans_attr(string: 'Login');?>">
                </div>
            </form>
        </div>
    </div>

<?php }); ?>
