<?php

use Qubus\EventDispatcher\ActionFilter\Action;

use function App\Shared\Helpers\get_auth_screen_logo;
use function App\Shared\Helpers\site_url;
use function Qubus\Security\Helpers\esc_attr__;
use function Qubus\Security\Helpers\t__;

$this->parent('framework::backend/layouts/auth-layout');
$this->block('auth', function () {
?>

    <div class="brand">
        <?=get_auth_screen_logo();?>
    </div>

    <div class="card fat">
        <div class="card-body">
            <?php Action::getInstance()->doAction('reset_form_top'); ?>
            <form method="post" action="<?= site_url('reset-password/'); ?>" class="my-login-validation" novalidate="" autocomplete="off">
                <div class="form-group">
                    <label for="username"><?=t__(msgid: 'Email', domain: 'devflow');?></label>
                    <input id="email" type="email" class="form-control" name="email" required="required" autofocus>
                    <div class="invalid-feedback">
                        <?=t__(msgid: 'Email is invalid.', domain: 'devflow');?>
                    </div>
                    <div class="form-text text-muted">
                        <?=t__(msgid: 'By clicking "Reset" the system will email you a new password.', domain: 'devflow');?>
                    </div>
                </div>

                <div class="form-group m-0">
                    <input type="submit" name="reset_password" class="btn btn-submit btn-block" value="<?=esc_attr__(string: 'Reset', domain: 'devflow');?>">
                </div>
            </form>
            <?php Action::getInstance()->doAction('reset_form_bottom'); ?>
        </div>
    </div>

<?php }); ?>