<?php
/**
 * User Create View
 */

use App\Application\Devflow;
use App\Shared\Services\Registry;
use Qubus\EventDispatcher\ActionFilter\Action;

use function App\Shared\Helpers\admin_url;
use function App\Shared\Helpers\generate_random_password;
use function App\Shared\Helpers\get_user_roles;
use function App\Shared\Helpers\selected;
use function Codefy\Framework\Helpers\trans_html;

$this->parent('framework::backend/layouts/admin-layout');
$this->block('backend', function ($params) {
Registry::getInstance()->{'set'}('screen_parent', 'users');
Registry::getInstance()->{'set'}('screen_child', 'create-user');
?>

    <script type="text/javascript">
        $(document).ready(function(){
            $("#password").hide();
            $("#hide_password").hide();
            $("#show_password").click(function(){
                $("#password").show(1000);
                $("#hide_password").show(1000);
                $("#show_password").hide(1000);
            });
            $("#hide_password").click(function(){
                $("#password").hide(1000);
                $("#hide_password").hide(1000);
                $("#show_password").show(1000);
            });
        });
    </script>

    <!-- form start -->
    <form id="user_form" method="post" action="<?= admin_url('user/create/'); ?>" data-toggle="validator" autocomplete="off">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="box box-solid">
                <div class="box-header with-border">
                    <i class="fa fa-user"></i>
                    <h3 class="box-title"><?= trans_html(string: 'Create User'); ?></h3>

                    <div class="pull-right">
                        <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> <?= trans_html(string: 'Save'); ?></button>
                        <button type="button" class="btn btn-primary" onclick="window.location = '<?= admin_url('user/'); ?>'"><i class="fa fa-ban"></i> <?= trans_html(string: 'Cancel'); ?></button>
                    </div>
                </div>
            </div>

            <!-- Main content -->
            <section class="content">

                <?php Action::getInstance()->doAction('admin_notices'); ?>

                <?= Devflow::$PHP->flash->display(); ?>

                <div class="row">
                    <!-- left column -->
                    <div class="col-md-9">
                        <!-- general form elements -->
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= trans_html(string: 'Name'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= trans_html(string: 'Username'); ?></strong></label>
                                    <input id="user_input" type="text" class="form-control" name="login" placeholder="Username" value="<?= $params['request']['login'] ?? ''; ?>" required/>
                                </div>

                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= trans_html(string: 'First Name'); ?></strong></label>
                                    <input id="fname" type="text" class="form-control" name="fname" value="<?= $params['request']['fname'] ?? ''; ?>" required/>
                                </div>

                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'Middle Name'); ?></strong></label>
                                    <input id="mname" type="text" class="form-control" name="mname" value="<?= $params['request']['mname'] ?? ''; ?>" />
                                </div>

                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= trans_html(string: 'Last Name'); ?></strong></label>
                                    <input id="lname" type="text" class="form-control" name="lname" value="<?= $params['request']['lname'] ?? ''; ?>" required/>
                                </div>

                                <?php
                                /**
                                 * Fires at the end of the 'Name' section on the 'Create User' screen.
                                 */
                                Action::getInstance()->doAction('create_user_profile_name');
                                ?>
                            </div>
                        </div>

                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= trans_html(string: 'Contact info'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">

                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= trans_html(string: 'Email'); ?></strong></label>
                                    <input id="email" type="email" class="form-control" name="email" value="<?= $params['request']['email'] ?? ''; ?>" required/>
                                </div>

                                <?php
                                /**
                                 * Fires at the end of the 'Contact info' section on the 'Create User' screen.
                                 */
                                Action::getInstance()->doAction('create_user_profile_contact');
                                ?>

                            </div>
                        </div>

                        <div id="send_email" class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= trans_html(string: 'Email / Password'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'Send Email'); ?></strong></label>
                                    <div class="ios-switch switch-md">
                                        <input type="hidden" class="js-switch" name="sendemail" value="0" />
                                        <input type="checkbox" class="js-switch" name="sendemail" value="1" />
                                        <div>
                                            <p class="help-block"><?=trans_html(string: 'Send username & password to the user.');?></p>
                                        </div>

                                        <div class="form-group password">
                                            <label><strong><span style="color: red; ">*</span> <?= trans_html(string: 'Password'); ?></strong></label>
                                            <input id="password" type="text" class="form-control" name="pass" value="<?= generate_random_password(length: 28); ?>" required/><br />
                                            <button type="button" class="btn btn-default" id="show_password"><?= trans_html(string: 'Show Password'); ?></button>
                                            <button type="button" class="btn btn-primary" id="hide_password"><?= trans_html(string: 'Hide Password'); ?></button>
                                        </div>

                                        <?php
                                        /**
                                         * Fires at the end of the 'Email / Password' section on the 'Create User' screen.
                                         */
                                        Action::getInstance()->doAction('create_user_profile_credentials');
                                        ?>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box -->
                    </div>

                    <div class="col-md-3">
                        <!-- general form elements -->
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= trans_html(string: 'User Status'); ?></h3>
                            </div>
                            <!-- /.box-header -->

                            <div class="box-body">
                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= trans_html(string: 'Status'); ?></strong></label>
                                    <select class="form-control select2" name="status" style="width: 100%;" required>
                                        <option value=""> ---------------------- </option>
                                        <option value="A"<?= selected('A', $params['request']['status'] ?? '', false); ?>><?= trans_html(string: 'Active'); ?></option>
                                        <option value="I"<?= selected('I', $params['request']['status'] ?? '', false); ?>><?= trans_html(string: 'Inactive'); ?></option>
                                        <option value="S"<?= selected('S', $params['request']['status'] ?? '', false); ?>><?= trans_html(string: 'Spammer'); ?></option>
                                        <option value="B"<?= selected('B', $params['request']['status'] ?? '', false); ?>><?= trans_html(string: 'Blocked'); ?></option>
                                    </select>
                                    <p class="help-block"><?= trans_html(string: 'If the account is Inactive, the user will be incapable of logging in.'); ?></p>
                                </div>
                            </div>

                        </div>

                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= trans_html(string: 'User Role'); ?></h3>
                            </div>
                            <!-- /.box-header -->

                            <div class="box-body">
                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= trans_html(string: 'Role'); ?></strong></label>
                                    <select class="form-control select2" name="role" style="width: 100%;" required>
                                        <option value=""> ---------------------- </option>
                                        <?php foreach (get_user_roles() as $role => $permissions) : ?>
                                            <option value="<?=$role;?>"<?=selected($role, $params['request']['role'] ?? '', false);?>><?=$role;?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </form>
    <!-- form end -->
<?php }); ?>
