<?php
/**
 * User Create View
 */

use App\Application\Devflow;
use App\Shared\Services\Registry;
use Qubus\EventDispatcher\ActionFilter\Action;

use function App\Shared\Helpers\admin_url;
use function App\Shared\Helpers\generate_random_password;
use function App\Shared\Helpers\get_user_roles;
use function App\Shared\Helpers\get_users_dropdown;
use function App\Shared\Helpers\selected;
use function Qubus\Security\Helpers\esc_html__;

$this->parent('framework::backend/layouts/admin-layout');
$this->block('backend', function ($params) {
Registry::getInstance()->{'set'}('screen_parent', 'users');
Registry::getInstance()->{'set'}('screen_child', 'create-user');
?>

    <script type="text/javascript">
        $(document).ready(function(){
            $('#user_select').on('change', function(e) {
                $.ajax({
                    type    : 'POST',
                    url     : "<?=admin_url('user/lookup/');?>",
                    dataType: 'json',
                    data    : $('#user_form').serialize(),
                    cache: false,
                    success: function( data ) {
                        for(let id in data) {
                            $(id).val( data[id] );
                        }
                    }
                });
            });
        });

        $(document).ready(function(){
            $('[name^="check"]').on('change', function() {
                if( $('#user_select').prop('disabled')) {
                    $('#user_select').prop('disabled',false);
                    $('#user_input').prop('disabled',true);
                    $('#send_email').hide();
                } else {
                    $('#user_input').prop('disabled',false);
                    $('#user_select').prop('disabled',true);
                    $('#send_email').show();
                }
            });

        });

        $(document).ready(function(){
            $("#password").hide();
            $("#hide_password").hide();
            $("#show_password").click(function(){
                $("#password").show(1000);
                $("#hide_password").show(1000);
                $("#show_password").hide(1000);
            });
            $("#hide_password").click(function(){
                $("#password").hide(1000);
                $("#hide_password").hide(1000);
                $("#show_password").show(1000);
            });
        });
    </script>

    <!-- form start -->
    <form id="user_form" method="post" action="<?= admin_url('user/create/'); ?>" data-toggle="validator" autocomplete="off">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="box box-solid">
                <div class="box-header with-border">
                    <i class="fa fa-user"></i>
                    <h3 class="box-title"><?= esc_html__(string: 'Create User', domain: 'devflow'); ?></h3>

                    <div class="pull-right">
                        <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> <?= esc_html__(string: 'Save', domain: 'devflow'); ?></button>
                        <button type="button" class="btn btn-primary" onclick="window.location = '<?= admin_url('user/'); ?>'"><i class="fa fa-ban"></i> <?= esc_html__(string: 'Cancel', domain: 'devflow'); ?></button>
                    </div>
                </div>
            </div>

            <!-- Main content -->
            <section class="content">

                <?php Action::getInstance()->doAction('admin_notices'); ?>

                <?= Devflow::inst()::$APP->flash->display(); ?>

                <div class="row">
                    <!-- left column -->
                    <div class="col-md-9">
                        <!-- general form elements -->
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= esc_html__(string: 'Name', domain: 'devflow'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= esc_html__(string: 'Username', domain: 'devflow'); ?></strong></label>
                                    <div class="clearfix">
                                        <input type="checkbox" name="check" checked="checked"/> <?=esc_html__(string: 'New User?', domain: 'devflow');?>
                                    </div>

                                    <div class="clearfix">&nbsp;</div>

                                    <div class="clearfix">
                                        <p style="margin-top:.6em;"><input id="user_input" type="text" class="form-control" name="login" placeholder="Username" value="<?= $params['request']['login'] ?? ''; ?>" /></p>
                                    </div>

                                    <select id="user_select" class="form-control select2" name="id" style="width: 100%;" disabled="disabled">
                                        <option value=""> ------------Existing User?------------ </option>
                                        <?php get_users_dropdown($params['request']['id'] ?? ''); ?>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= esc_html__(string: 'First Name', domain: 'devflow'); ?></strong></label>
                                    <input id="fname" type="text" class="form-control" name="fname" value="<?= $params['request']['fname'] ?? ''; ?>" required/>
                                </div>

                                <div class="form-group">
                                    <label><strong><?= esc_html__(string: 'Middle Name', domain: 'devflow'); ?></strong></label>
                                    <input id="mname" type="text" class="form-control" name="mname" value="<?= $params['request']['mname'] ?? ''; ?>" />
                                </div>

                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= esc_html__(string: 'Last Name', domain: 'devflow'); ?></strong></label>
                                    <input id="lname" type="text" class="form-control" name="lname" value="<?= $params['request']['lname'] ?? ''; ?>" required/>
                                </div>

                                <?php
                                /**
                                 * Fires at the end of the 'Name' section on the 'Create User' screen.
                                 */
                                Action::getInstance()->doAction('create_user_profile_name');
                                ?>
                            </div>
                        </div>

                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= esc_html__(string: 'Contact info', domain: 'devflow'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">

                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= esc_html__(string: 'Email', domain: 'devflow'); ?></strong></label>
                                    <input id="email" type="email" class="form-control" name="email" value="<?= $params['request']['email'] ?? ''; ?>" required/>
                                </div>

                                <?php
                                /**
                                 * Fires at the end of the 'Contact info' section on the 'Create User' screen.
                                 */
                                Action::getInstance()->doAction('create_user_profile_contact');
                                ?>

                            </div>
                        </div>

                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= esc_html__(string: 'User Status', domain: 'devflow'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">

                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= esc_html__(string: 'Status', domain: 'devflow'); ?></strong></label>
                                    <select class="form-control select2" name="status" style="width: 100%;" required>
                                        <option value=""> ---------------------- </option>
                                        <option value="A"<?= selected('A', $params['request']['status'] ?? '', false); ?>><?= esc_html__(string: 'Active', domain: 'devflow'); ?></option>
                                        <option value="I"<?= selected('I', $params['request']['status'] ?? '', false); ?>><?= esc_html__(string: 'Inactive', domain: 'devflow'); ?></option>
                                        <option value="S"<?= selected('S', $params['request']['status'] ?? '', false); ?>><?= esc_html__(string: 'Spammer', domain: 'devflow'); ?></option>
                                        <option value="B"<?= selected('B', $params['request']['status'] ?? '', false); ?>><?= esc_html__(string: 'Blocked', domain: 'devflow'); ?></option>
                                    </select>
                                    <p class="help-block"><?= esc_html__(string: 'If the account is Inactive, the user will be incapable of logging in.', domain: 'devflow'); ?></p>
                                </div>
                            </div>
                        </div>

                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= esc_html__(string: 'User Role', domain: 'devflow'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">

                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= esc_html__(string: 'Role', domain: 'devflow'); ?></strong></label>
                                    <select class="form-control select2" name="role" style="width: 100%;" required>
                                        <option value=""> ---------------------- </option>
                                        <?php foreach (get_user_roles() as $role => $permissions) : ?>
                                        <option value="<?=$role;?>"<?=selected($role, $params['request']['role'] ?? '', false);?>><?=$role;?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div id="send_email" class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= esc_html__(string: 'Email / Password', domain: 'devflow'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">

                                <div class="form-group">
                                    <label><strong><?= esc_html__(string: 'Send Email', domain: 'devflow'); ?></strong></label>
                                    <div class="ios-switch switch-md">
                                        <input type="hidden" class="js-switch" name="sendemail" value="0" />
                                        <input type="checkbox" class="js-switch" name="sendemail" value="1" />
                                        <div>
                                            <p class="help-block"><?=esc_html__(string: 'Send username & password to the user.', domain: 'devflow');?></p>
                                        </div>

                                        <div class="form-group password">
                                            <label><strong><span style="color: red; ">*</span> <?= esc_html__(string: 'Password', domain: 'devflow'); ?></strong></label>
                                            <input id="password" type="text" class="form-control" name="pass" value="<?= generate_random_password(length: 28); ?>" required/><br />
                                            <button type="button" class="btn btn-default" id="show_password"><?= esc_html__(string: 'Show Password', domain: 'devflow'); ?></button>
                                            <button type="button" class="btn btn-primary" id="hide_password"><?= esc_html__(string: 'Hide Password', domain: 'devflow'); ?></button>
                                        </div>

                                        <?php
                                        /**
                                         * Fires at the end of the 'Email / Password' section on the 'Create User' screen.
                                         */
                                        Action::getInstance()->doAction('create_user_profile_credentials');
                                        ?>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box -->

            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </form>
    <!-- form end -->
<?php }); ?>