<?php
/**
 * User's List View
 */

use App\Application\Devflow;
use App\Domain\User\Enum\UserStatus;
use App\Shared\Services\Registry;
use Qubus\EventDispatcher\ActionFilter\Action;

use function App\Shared\Helpers\admin_url;
use function App\Shared\Helpers\ae;
use function App\Shared\Helpers\get_current_user_id;
use function App\Shared\Helpers\get_name;
use function App\Shared\Helpers\get_user_option;
use function App\Shared\Helpers\get_userdata;
use function App\Shared\Helpers\get_users_reassign;
use function Codefy\Framework\Helpers\trans_attr;
use function Codefy\Framework\Helpers\trans_html;
use function Qubus\Security\Helpers\esc_html;

$this->parent('framework::backend/layouts/admin-layout');
$this->block('backend', function ($params) {
Registry::getInstance()->{'set'}('screen_parent', 'users');
Registry::getInstance()->{'set'}('screen_child', 'all-users');
?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="box box-solid">
            <div class="box-header with-border">
                <i class="fa fa-user"></i>
                <h3 class="box-title"><?= trans_html(string: 'Users'); ?></h3>

                <div class="pull-right">
                    <button type="button"<?=ae('create:users');?> class="btn btn-warning" onclick="window.location='<?=admin_url('user/create/');?>'"><i class="fa fa-plus"></i> <?= trans_html(string: 'New User'); ?></button>
                </div>
            </div>
        </div>

        <!-- Main content -->
        <section class="content">

            <?php Action::getInstance()->doAction('admin_notices'); ?>

            <?= Devflow::$PHP->flash->display(); ?>

            <!-- SELECT2 EXAMPLE -->
            <div class="box box-default">
                <div class="box-body">
                    <table id="user" class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th class="text-center"><?= trans_html(string: 'Username'); ?></th>
                            <th class="text-center"><?= trans_html(string: 'First Name'); ?></th>
                            <th class="text-center"><?= trans_html(string: 'Last Name'); ?></th>
                            <th class="text-center"><?= trans_html(string: 'Status'); ?></th>
                            <th class="text-center"><?= trans_html(string: 'Role'); ?></th>
                            <th class="text-center"><?= trans_html(string: 'Action'); ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($params['users'] as $user) : $data = get_userdata(esc_html($user['user_id'])); ?>
                            <tr class="gradeX">
                                <td class="text-center"><?= esc_html($user['user_login']); ?></td>
                                <td class="text-center"><?= esc_html($user['user_fname']); ?></td>
                                <td class="text-center"><?= esc_html($user['user_lname']); ?></td>
                                <td class="text-center">
                                    <?php $status = get_user_option('status', esc_html($user['user_id'])); ?>
                                    <span class="label <?=UserStatus::{$status}->color();?>" style="font-size:1em;font-weight: bold;">
                                        <?=UserStatus::{$status}->label();?>
                                    </span>
                                </td>
                                <td class="text-center"><?=$data->role;?></td>
                                <td class="text-center">
                                    <?php if (esc_html($user['user_id']) === get_current_user_id()) : ?>
                                        <a href="<?= admin_url('user/profile/'); ?>" data-toggle="tooltip" data-placement="top" title="<?= trans_attr(string: 'Update'); ?>"><button type="button" class="btn bg-yellow"><i class="fa fa-edit"></i></button></a>
                                    <?php else : ?>
                                        <a href="<?= admin_url(sprintf('user/%s/', esc_html($user['user_id']) )); ?>" data-toggle="tooltip" data-placement="top" title="<?= trans_attr(string: 'Update'); ?>"><button type="button" class="btn bg-yellow"><i class="fa fa-edit"></i></button></a>
                                    <?php endif; ?>
                                    <a href="<?= admin_url(sprintf('user/%s/reset-password/', esc_html($user['user_id']))); ?>" data-toggle="tooltip" data-placement="top" title="<?= trans_attr(string: 'Reset Password'); ?>"><button type="button" class="btn bg-purple"><i class="fa fa-redo"></i></button></a>
                                    <?php if (!isset($_COOKIE['SWITCH_USERBACK']) && esc_html($user['user_id']) !== get_current_user_id()) : ?>
                                        <a<?= ae('switch:user'); ?> href="<?= admin_url(sprintf('user/%s/switch-to/', esc_html($user['user_id']))); ?>" data-toggle="tooltip" data-placement="top" title="<?= trans_attr(string: 'Switch to'); ?>"><button type="button" class="btn bg-blue"><i class="fa fa-exchange-alt"></i></button></a>
                                    <?php endif; ?>
                                    <?php if ($data->role !== 'super' && esc_html($user['user_id']) !== get_current_user_id()) : ?>
                                        <a<?= ae('delete:users'); ?> href="#" data-toggle="modal" data-target="#delete-<?= esc_html($user['user_id']); ?>"><button type="button" class="btn bg-red"><i class="fa fa-trash"></i></button></a>
                                    <?php endif; ?>

                                    <div class="modal" id="delete-<?=esc_html($user['user_id']);?>">
                                        <form method="post" action="<?=admin_url('user/' . esc_html($user['user_id']) . '/d/');?>">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span></button>
                                                        <h4 class="modal-title"><?= get_name(esc_html($user['user_id'])); ?></h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p><?= trans_html(string: 'Are you sure you want to remove the user from this site?'); ?></p>
                                                        <div class="alert alert-info"><?=trans_html(string: "Would you like to assign this user's content to a different user? Choose below.");?></div>
                                                        <select class="form-control select2" name="assign_id" style="width: 100%;">
                                                            <option value="null">&nbsp;</option>
                                                            <?php get_users_reassign(esc_html($user['user_id'])); ?>
                                                        </select>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <input type="hidden" name="user_id" value="<?=esc_html($user['user_id']);?>" />
                                                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal"><?= trans_html(string: 'Close'); ?></button>
                                                        <button type="submit" class="btn btn-primary"><?= trans_html(string: 'Confirm'); ?></button>
                                                    </div>
                                                </div>
                                                <!-- /.modal-content -->
                                            </div>
                                            <!-- /.modal-dialog -->
                                        </form>
                                    </div>
                                    <!-- /.modal -->
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <th class="text-center"><?= trans_html(string: 'Username'); ?></th>
                            <th class="text-center"><?= trans_html(string: 'First Name'); ?></th>
                            <th class="text-center"><?= trans_html(string: 'Last Name'); ?></th>
                            <th class="text-center"><?= trans_html(string: 'Status'); ?></th>
                            <th class="text-center"><?= trans_html(string: 'Role'); ?></th>
                            <th class="text-center"><?= trans_html(string: 'Action'); ?></th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
<?php }); ?>
