<?php
/**
 * Update Profile View
 */

use App\Application\Devflow;
use App\Shared\Services\Registry;
use Qubus\EventDispatcher\ActionFilter\Action;

use Qubus\EventDispatcher\ActionFilter\Filter;

use function App\Shared\Helpers\admin_url;
use function App\Shared\Helpers\ae;
use function App\Shared\Helpers\checked;
use function App\Shared\Helpers\cms_dropdown_languages;
use function App\Shared\Helpers\cms_upload_image;
use function App\Shared\Helpers\generate_timezone_list;
use function App\Shared\Helpers\get_user_avatar;
use function App\Shared\Helpers\get_user_option;
use function App\Shared\Helpers\selected;
use function Codefy\Framework\Helpers\trans;
use function Codefy\Framework\Helpers\trans_html;
use function Qubus\Security\Helpers\purify_html;

$this->parent('framework::backend/layouts/admin-layout');
$this->block('backend', function ($param) {
Registry::getInstance()->{'set'}('screen_parent', 'users');
Registry::getInstance()->{'set'}('screen_child', 'profile');
?>

<?=cms_upload_image();?>

    <!-- form start -->
    <form method="post" action="<?= admin_url('user/profile/'); ?>" data-toggle="validator" autocomplete="off">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="box box-solid">
                <div class="box-header with-border">
                    <i class="fa fa-user"></i>
                    <h3 class="box-title"><?= trans_html(string: 'Profile'); ?></h3>

                    <div class="pull-right">
                        <input type="hidden" name="id" value="<?=$param['user']->id;?>" />
                        <input type="hidden" name="role" value="<?= get_user_option('role', $param['user']->id); ?>" />
                        <input type="hidden" name="status" value="<?= get_user_option('status', $param['user']->id); ?>" />
                        <button type="submit" class="btn btn-success"><i class="fa fa-pencil-alt"></i> <?= trans_html(string: 'Update'); ?></button>
                        <button type="button"<?=ae('manage:users');?> class="btn btn-primary" onclick="window.location = '<?= admin_url('user/'); ?>'"><i class="fa fa-ban"></i> <?= trans_html(string: 'Cancel'); ?></button>
                    </div>
                </div>
            </div>

            <!-- Main content -->
            <section class="content">

                <?php Action::getInstance()->doAction('admin_notices'); ?>

                <?= Devflow::$PHP->flash->display(); ?>

                <div class="row">
                    <!-- left column -->
                    <div class="col-md-9">
                        <!-- general form elements -->
                        <?php if('' !== get_user_option('role', $param['user']->id)) : ?>
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= trans_html(string: 'Layout Options'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'Fixed Layout'); ?></strong></label>
                                    <div class="ios-switch switch-md pull-left">
                                        <input type="hidden" class="js-switch" name="adminLayout" value="0" />
                                        <input type="checkbox" class="js-switch" name="adminLayout"<?= checked(1, get_user_option('admin.layout', $param['user']->id)); ?> value="1" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'Toggle Sidebar'); ?></strong></label>
                                    <div class="ios-switch switch-md pull-left">
                                        <input type="hidden" class="js-switch" name="adminSidebar" value="0" />
                                        <input type="checkbox" class="js-switch" name="adminSidebar"<?= checked(1, get_user_option('admin.sidebar', $param['user']->id)); ?> value="1" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'Admin Skin'); ?></strong></label>
                                    <ul style="list-style: none;margin:0px 0px 0px -30px;">
                                        <li style="float:left; width: 25%; padding: 5px;">
                                            <input type="radio" class="flat-red" name="adminSkin"<?= checked('skin-blue', get_user_option('admin.skin', $param['user']->id)); ?> value="skin-blue" />
                                            <a href="javascript:void(0)" data-skin="skin-blue" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                                                <div><span style="display:block; width: 20%; float: left; height: 7px; background: #367fa9"></span><span class="bg-light-blue" style="display:block; width: 80%; float: left; height: 7px;"></span></div>
                                                <div><span style="display:block; width: 20%; float: left; height: 20px; background: #222d32"></span><span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7"></span></div>
                                            </a>
                                        </li>
                                        <li style="float:left; width: 25%; padding: 5px;">
                                            <input type="radio" class="flat-red" name="adminSkin"<?= checked('skin-black', get_user_option('admin.skin', $param['user']->id)); ?> value="skin-black" />
                                            <a href="javascript:void(0)" data-skin="skin-black" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                                                <div style="box-shadow: 0 0 2px rgba(0,0,0,0.1)" class="clearfix"><span style="display:block; width: 20%; float: left; height: 7px; background: #fefefe"></span><span style="display:block; width: 80%; float: left; height: 7px; background: #fefefe"></span></div>
                                                <div><span style="display:block; width: 20%; float: left; height: 20px; background: #222"></span><span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7"></span></div>
                                            </a>
                                        </li>
                                        <li style="float:left; width: 25%; padding: 5px;">
                                            <input type="radio" class="flat-red" name="adminSkin"<?= checked('skin-purple', get_user_option('admin.skin', $param['user']->id)); ?> value="skin-purple" />
                                            <a href="javascript:void(0)" data-skin="skin-purple" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                                                <div><span style="display:block; width: 20%; float: left; height: 7px;" class="bg-purple-active"></span><span class="bg-purple" style="display:block; width: 80%; float: left; height: 7px;"></span></div>
                                                <div><span style="display:block; width: 20%; float: left; height: 20px; background: #222d32"></span><span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7"></span></div>
                                            </a>
                                        </li>
                                        <li style="float:left; width: 25%; padding: 5px;">
                                            <input type="radio" class="flat-red" name="adminSkin"<?= checked('skin-green', get_user_option('admin.skin', $param['user']->id)); ?> value="skin-green" />
                                            <a href="javascript:void(0)" data-skin="skin-green" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                                                <div><span style="display:block; width: 20%; float: left; height: 7px;" class="bg-green-active"></span><span class="bg-green" style="display:block; width: 80%; float: left; height: 7px;"></span></div>
                                                <div><span style="display:block; width: 20%; float: left; height: 20px; background: #222d32"></span><span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7"></span></div>
                                            </a>
                                        </li>
                                        <li style="float:left; width: 25%; padding: 5px;">
                                            <input type="radio" class="flat-red" name="adminSkin"<?= checked('skin-red', get_user_option('admin.skin', $param['user']->id)); ?> value="skin-red" />
                                            <a href="javascript:void(0)" data-skin="skin-red" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                                                <div><span style="display:block; width: 20%; float: left; height: 7px;" class="bg-red-active"></span><span class="bg-red" style="display:block; width: 80%; float: left; height: 7px;"></span></div>
                                                <div><span style="display:block; width: 20%; float: left; height: 20px; background: #222d32"></span><span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7"></span></div>
                                            </a>
                                        </li>
                                        <li style="float:left; width: 25%; padding: 5px;">
                                            <input type="radio" class="flat-red" name="adminSkin"<?= checked('skin-yellow', get_user_option('admin.skin', $param['user']->id)); ?> value="skin-yellow" />
                                            <a href="javascript:void(0)" data-skin="skin-yellow" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                                                <div><span style="display:block; width: 20%; float: left; height: 7px;" class="bg-yellow-active"></span><span class="bg-yellow" style="display:block; width: 80%; float: left; height: 7px;"></span></div>
                                                <div><span style="display:block; width: 20%; float: left; height: 20px; background: #222d32"></span><span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7"></span></div>
                                            </a>
                                        </li>
                                        <li style="float:left; width: 25%; padding: 5px;">
                                            <input type="radio" class="flat-red" name="adminSkin"<?= checked('skin-blue-light', get_user_option('admin.skin', $param['user']->id)); ?> value="skin-blue-light" />
                                            <a href="javascript:void(0)" data-skin="skin-blue-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                                                <div><span style="display:block; width: 20%; float: left; height: 7px; background: #367fa9"></span><span class="bg-light-blue" style="display:block; width: 80%; float: left; height: 7px;"></span></div>
                                                <div><span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc"></span><span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7"></span></div>
                                            </a>
                                        </li>
                                        <li style="float:left; width: 25%; padding: 5px;">
                                            <input type="radio" class="flat-red" name="adminSkin"<?= checked('skin-black-light', get_user_option('admin.skin', $param['user']->id)); ?> value="skin-black-light" />
                                            <a href="javascript:void(0)" data-skin="skin-black-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                                                <div style="box-shadow: 0 0 2px rgba(0,0,0,0.1)" class="clearfix"><span style="display:block; width: 20%; float: left; height: 7px; background: #fefefe"></span><span style="display:block; width: 80%; float: left; height: 7px; background: #fefefe"></span></div>
                                                <div><span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc"></span><span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7"></span></div>
                                            </a>
                                        </li>
                                        <li style="float:left; width: 25%; padding: 5px;">
                                            <input type="radio" class="flat-red" name="adminSkin"<?= checked('skin-purple-light', get_user_option('admin.skin', $param['user']->id)); ?> value="skin-purple-light" />
                                            <a href="javascript:void(0)" data-skin="skin-purple-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                                                <div><span style="display:block; width: 20%; float: left; height: 7px;" class="bg-purple-active"></span><span class="bg-purple" style="display:block; width: 80%; float: left; height: 7px;"></span></div>
                                                <div><span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc"></span><span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7"></span></div>
                                            </a>
                                        </li>
                                        <li style="float:left; width: 25%; padding: 5px;">
                                            <input type="radio" class="flat-red" name="adminSkin"<?= checked('skin-green-light', get_user_option('admin.skin', $param['user']->id)); ?> value="skin-green-light" />
                                            <a href="javascript:void(0)" data-skin="skin-green-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                                                <div><span style="display:block; width: 20%; float: left; height: 7px;" class="bg-green-active"></span><span class="bg-green" style="display:block; width: 80%; float: left; height: 7px;"></span></div>
                                                <div><span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc"></span><span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7"></span></div>
                                            </a>
                                        </li>
                                        <li style="float:left; width: 25%; padding: 5px;">
                                            <input type="radio" class="flat-red" name="adminSkin"<?= checked('skin-red-light', get_user_option('admin.skin', $param['user']->id)); ?> value="skin-red-light" />
                                            <a href="javascript:void(0)" data-skin="skin-red-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                                                <div><span style="display:block; width: 20%; float: left; height: 7px;" class="bg-red-active"></span><span class="bg-red" style="display:block; width: 80%; float: left; height: 7px;"></span></div>
                                                <div><span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc"></span><span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7"></span></div>
                                            </a>
                                        </li>
                                        <li style="float:left; width: 25%; padding: 5px;">
                                            <input type="radio" class="flat-red" name="adminSkin"<?= checked('skin-yellow-light', get_user_option('admin.skin', $param['user']->id)); ?> value="skin-yellow-light" />
                                            <a href="javascript:void(0)" data-skin="skin-yellow-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                                                <div><span style="display:block; width: 20%; float: left; height: 7px;" class="bg-yellow-active"></span><span class="bg-yellow" style="display:block; width: 80%; float: left; height: 7px;"></span></div>
                                                <div><span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc"></span><span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7"></span></div>
                                            </a>
                                        </li>
                                    </ul>
                                </div>

                                <?php
                                /**
                                 * Fires at the end of the 'Layout Options' section on the 'Profile' screen.
                                 * @param array $param['user'] User object.
                                 */
                                Action::getInstance()->doAction('user_profile_layout', $param['user']);
                                ?>
                            </div>
                        </div>
                        <?php endif; ?>

                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= trans_html(string: 'Name'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'Username'); ?></strong></label>
                                    <input type="text" class="form-control" id="user_login" name="login" value="<?=$param['user']->login;?>" readonly="readonly" required/>
                                    <button type="button" class="btn btn-primary" id="enable_button" style="display:none"><?= trans_html(string: 'Change username'); ?></button>
                                    <button type="button" class="btn btn-danger" id="disable_button" style="display:none"><?= trans_html(string: 'Cancel'); ?></button>
                                </div>

                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= trans_html(string: 'First Name'); ?></strong></label>
                                    <input type="text" class="form-control" name="fname" value="<?=$param['user']->fname;?>" required>
                                </div>

                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'Middle Name'); ?></strong></label>
                                    <input type="text" class="form-control" name="mname" value="<?=$param['user']->mname;?>">
                                </div>

                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= trans_html(string: 'Last Name'); ?></strong></label>
                                    <input type="text" class="form-control" name="lname" value="<?=$param['user']->lname;?>" required>
                                </div>

                                <?php
                                /**
                                 * Fires at the end of the 'Name' section on the 'Profile' screen.
                                 * @param array $param['user'] User object.
                                 */
                                Action::getInstance()->doAction('user_profile_name', $param['user']);
                                ?>
                            </div>
                        </div>

                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= trans_html(string: 'Contact info'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">

                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= trans_html(string: 'Email'); ?></strong></label>
                                    <input type="email" class="form-control" name="email" value="<?=$param['user']->email;?>" required>
                                </div>

                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'URL'); ?></strong></label>
                                    <input type="text" class="form-control" name="url" value="<?=$param['user']->url;?>" />
                                </div>

                                <?php
                                /**
                                 * Fires at the end of the 'Contact info' section on the 'Profile' screen.
                                 *
                                 * @param array $param['user'] User object.
                                 */
                                Action::getInstance()->doAction('user_profile_contact', $param['user']);
                                ?>

                            </div>
                        </div>

                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= trans_html(string: 'About yourself'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">

                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'Biography'); ?></strong></label>
                                    <textarea class="form-control" name="bio" rows="5"><?=$param['user']->bio;?></textarea>
                                </div>

                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'Profile Picture'); ?></strong></label>
                                    <div><?= get_user_avatar($param['user']->email, 100);?></div>
                                    <p class="help-block"><?= sprintf(purify_html(string: trans('You can change your profile picture on <a href="%s">Gravatar</a>.')), '//en.gravatar.com/'); ?></p>
                                </div>

                                <?php
                                /**
                                 * Fires at the end of the 'About yourself' section on the 'Profile' screen.
                                 * @param array $param['user'] User object.
                                 */
                                Action::getInstance()->doAction('user_profile_about', $param['user']);
                                ?>

                            </div>
                        </div>

                        <?php
                        /**
                         * Fires after the 'About yourself' section on the 'Profile' screen.
                         * @param array $param['user'] User object.
                         */
                        Action::getInstance()->doAction('user_profile', $param['user']);
                        ?>
                        <?=Filter::getInstance()->applyFilter('user_attribute_box_extended', $param['user']->id);?>

                    </div>

                    <div class="col-md-3">
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= trans_html(string: 'Date/Time'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'Timezone'); ?></strong></label>
                                    <select class="form-control select2" name="timezone" style="width: 100%;">
                                        <option value=""> ------------------------- </option>
                                        <?php foreach (generate_timezone_list() as $k => $v) : ?>
                                            <option value="<?=$k;?>"<?=selected($param['user']->timezone, $k, false); ?>><?=$v;?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'Date Format'); ?></strong></label>
                                    <input type="text" class="form-control" name="date_format" value="<?= $param['user']->dateFormat; ?>" />
                                </div>

                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'Time Format'); ?></strong></label>
                                    <input type="text" class="form-control" name="time_format" value="<?= $param['user']->timeFormat; ?>" />
                                </div>

                                <?php
                                /**
                                 * Fires at the end of the 'Date/Time' section on the 'Profile' screen.
                                 * @param array $param['user'] User object.
                                 */
                                Action::getInstance()->doAction('user_profile_datetime', $param['user']);
                                ?>
                            </div>
                        </div>

                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= trans_html(string: 'Locale'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'Language'); ?></strong></label>
                                    <select class="form-control select2" name="locale" style="width: 100%;">
                                        <option value=""> ------------------------- </option>
                                        <?php cms_dropdown_languages($param['user']->locale); ?>
                                    </select>
                                </div>

                                <?php
                                /**
                                 * Fires at the end of the 'Locale' section on the 'Profile' screen.
                                 * @param array $param['user'] User object.
                                 */
                                Action::getInstance()->doAction('user_profile_locale', $param['user']);
                                ?>

                            </div>
                        </div>
                        <?=Filter::getInstance()->applyFilter('user_attribute_box_side', $param['user']->id);?>
                    </div>
                </div>
                <!-- /.box -->

            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </form>
    <!-- form end -->
    <script>
        $("#disable_button").hide();
        $("#enable_button").show();

        $('#disable_button').click(function() {
            $("#disable_button").hide();
            $("#enable_button").show();
            $('#user_login').prop('readonly', true);
        });
        $('#enable_button').click(function() {
            $("#disable_button").show();
            $("#enable_button").hide();
            $('#user_login').prop('readonly', false);
        });
    </script>
    <?php
    /**
     * Fires before the user profile screen is fully loaded.
     */
    Action::getInstance()->doAction('enqueue_cms_editor');
    ?>
<?php }); ?>
