<?php

declare(strict_types=1);

use App\Application\Devflow;
use App\Infrastructure\Services\Options;
use App\Shared\Services\Registry;
use Qubus\EventDispatcher\ActionFilter\Action;

use function App\Shared\Helpers\admin_url;
use function App\Shared\Helpers\cms_dropdown_languages;
use function App\Shared\Helpers\generate_timezone_list;
use function App\Shared\Helpers\selected;
use function Qubus\Security\Helpers\esc_html__;

$this->parent('framework::backend/layouts/admin-layout');
$this->block('backend', function () {
Registry::getInstance()->{'set'}('screen_parent', 'options');
Registry::getInstance()->{'set'}('screen_child', 'options-general');

Action::getInstance()->doAction('options_init');

$option = Options::factory();
?>
    <!-- form start -->
    <form name="form" method="post" data-toggle="validator" action="<?= admin_url('general/'); ?>" id="form" autocomplete="off">
        <!-- Content Wrapper. Contains post content -->
        <div class="content-wrapper">
            <!-- Content Header (Post header) -->
            <div class="box box-solid">
                <div class="box-header with-border">
                    <i class="fa fa-cogs"></i>
                    <h3 class="box-title"><?= esc_html__(string: 'General Options', domain: 'devflow'); ?></h3>

                    <div class="pull-right">
                        <button type="submit" class="btn btn-success"><i class="fa fa-pencil-alt"></i> <?= esc_html__(string: 'Update', domain: 'devflow'); ?></button>
                    </div>
                </div>
            </div>

            <!-- Main content -->
            <section class="content">

                <?php Action::getInstance()->doAction('admin_notices'); ?>

                <?= Devflow::inst()::$APP->flash->display(); ?>

                <div class="row">
                    <!-- left column -->
                    <div class="col-md-9">
                        <!-- general form elements -->
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= esc_html__(string: 'General Options', domain: 'devflow'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= esc_html__(string: 'Site Name', domain: 'devflow'); ?></strong></label>
                                    <input type="text" class="form-control" name="sitename" value="<?= $option->read('sitename'); ?>" required/>
                                </div>
                                <div class="form-group">
                                    <label><strong><?= esc_html__(string: 'Site Description', domain: 'devflow'); ?></strong></label>
                                    <input type="text" class="form-control" name="site_description" value="<?= $option->read('site_description'); ?>" />
                                </div>
                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= esc_html__(string: 'Admin Email', domain: 'devflow'); ?></strong></label>
                                    <input type="text" class="form-control" name="admin_email" value="<?= $option->read('admin_email'); ?>" required/>
                                </div>
                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= esc_html__(string: 'Locale', domain: 'devflow'); ?></strong></label>
                                    <select class="form-control select2" name="site_locale" style="width: 100%;" required>
                                        <option>&nbsp;</option>
                                        <?php cms_dropdown_languages($option->read('site_locale')); ?>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= esc_html__(string: 'Cookie Expire', domain: 'devflow'); ?></strong></label>
                                    <input type="text" class="form-control" name="cookieexpire" value="<?= $option->read('cookieexpire'); ?>" required/>
                                </div>
                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= esc_html__(string: 'Cookie Path', domain: 'devflow'); ?></strong></label>
                                    <input type="text" class="form-control" name="cookiepath" value="<?= $option->read('cookiepath'); ?>" required/>
                                </div>
                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= esc_html__(string: 'System Timezone', domain: 'devflow'); ?></strong></label>
                                    <select class="form-control select2" name="site_timezone" style="width: 100%;" required>
                                        <option value=""> ------------------------- </option>
                                        <?php foreach (generate_timezone_list() as $k => $v) : ?>
                                            <option value="<?=$k;?>"<?=selected($option->read('site_timezone'), $k, false); ?>><?=$v;?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= esc_html__(string: 'API Key', domain: 'devflow'); ?></strong></label>
                                    <input type="text" class="form-control" name="api_key" value="<?= $option->read('api_key'); ?>" required/>
                                </div>
                                <?php Action::getInstance()->doAction('options_general_form'); ?>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.left column -->

                </div>
                <!--/.row -->
            </section>
            <!-- /.Main content -->
        </div>
    </form>
    <!-- /.Content Wrapper. Contains post content -->
<?php }); ?>