<?php

declare(strict_types=1);

use App\Application\Devflow;
use App\Shared\Services\Registry;
use Qubus\EventDispatcher\ActionFilter\Action;

use function Codefy\Framework\Helpers\trans_html;

$this->parent('framework::backend/layouts/admin-layout');
$this->block('backend', function () {
Registry::getInstance()->{'set'}('screen_parent', 'dashboard');
Registry::getInstance()->{'set'}('screen_child', 'home');
?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                <?= trans_html(string: 'Dashboard'); ?>
                <small><?= trans_html(string: 'Control panel'); ?></small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> <?= trans_html(string: 'Home'); ?></a></li>
                <li class="active"><?= trans_html(string: 'Dashboard'); ?></li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <?php Action::getInstance()->doAction('admin_notices'); ?>

            <?=Devflow::$PHP->flash->display();?>

            <div class="row">
                <?php //top widgets can go here.?>
            </div>
            <!-- /.row -->

            <!-- Main row -->
            <div class="row">
                <!-- Left col -->
                <section class="col-lg-6">

                    <?php Action::getInstance()->doAction('widget_left_column'); ?>

                </section>
                <!-- /.Left col -->

                <!-- Left col -->
                <section class="col-lg-6 connectedSortable">

                    <?php Action::getInstance()->doAction('widget_right_column'); ?>

                </section>
                <!-- /.Left col -->
            </div>
            <!-- /.row (main row) -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
<?php }); ?>
