<?php

use App\Application\Devflow;

use function App\Shared\Helpers\admin_url;
use function App\Shared\Helpers\get_auth_screen_logo;
use function Qubus\Security\Helpers\esc_attr__;
use function Qubus\Security\Helpers\t__;

$this->parent('framework::backend/layouts/auth-layout');
$this->block('auth', function () {
?>

    <div class="brand">
        <?=get_auth_screen_logo();?>
        <?=Devflow::inst()::$APP->flash->display();?>
    </div>

    <div class="card fat">
        <div class="card-body">
            <form method="post" action="<?=admin_url('install/');?>" class="my-login-validation" novalidate="" autocomplete="off">
                <div class="form-group">
                    <p>
                        <?=t__(
                            msgid: sprintf(
                                'Please make sure that you follow the <a href="%s">system setup</a> before you click the install button.',
                                    'https://github.com/qubus/codefy/wiki/Installation'
                            ),
                            domain: 'devflow'
                        );?>
                    </p>
                </div>

                <div class="form-group m-0">
                    <input type="submit" name="install-submit" class="btn btn-submit btn-block" value="<?=esc_attr__(string: 'Install', domain: 'devflow');?>">
                </div>
            </form>
        </div>
    </div>

<?php }); ?>