<?php

declare(strict_types=1);

use App\Application\Devflow;
use App\Shared\Services\Registry;
use Qubus\EventDispatcher\ActionFilter\Action;

use function App\Shared\Helpers\admin_url;
use function App\Shared\Helpers\cms_charset;
use function App\Shared\Helpers\get_option;
use function Codefy\Framework\Helpers\trans_html;

$this->parent('framework::backend/layouts/admin-layout');
$this->block('backend', function () {
Registry::getInstance()->{'set'}('screen_parent', 'options');
Registry::getInstance()->{'set'}('screen_child', 'options-reading');

Action::getInstance()->doAction('options_init');
?>
    <!-- form start -->
    <form name="form" method="post" data-toggle="validator" action="<?= admin_url('reading/'); ?>" id="form" autocomplete="off">
        <!-- Content Wrapper. Contains post content -->
        <div class="content-wrapper">
            <!-- Content Header (Post header) -->
            <div class="box box-solid">
                <div class="box-header with-border">
                    <i class="fa fa-cogs"></i>
                    <h3 class="box-title"><?= trans_html(string: 'Reading Options'); ?></h3>

                    <div class="pull-right">
                        <button type="submit" class="btn btn-success"><i class="fa fa-pencil-alt"></i> <?= trans_html(string: 'Update'); ?></button>
                    </div>
                </div>
            </div>

            <!-- Main content -->
            <section class="content">

                <?php Action::getInstance()->doAction('admin_notices'); ?>

                <?= Devflow::$PHP->flash->display(); ?>

                <div class="row">
                    <!-- left column -->
                    <div class="col-md-9">
                        <!-- general form elements -->
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= trans_html(string: 'Reading Options'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'Charset'); ?></strong></label>
                                    <?=cms_charset(get_option(key: 'charset', default: 'utf8'));?>
                                </div>
                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'Content per Page'); ?></strong></label>
                                    <input type="text" class="form-control" name="content_per_page" value="<?= get_option(key: 'content_per_page'); ?>" />
                                </div>
                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'Date Format'); ?></strong></label>
                                    <input type="text" class="form-control" name="date_format" value="<?= get_option(key: 'date_format'); ?>" />
                                </div>
                                <div class="form-group">
                                    <label><strong><?= trans_html(string: 'Time Format'); ?></strong></label>
                                    <input type="text" class="form-control" name="time_format" value="<?= get_option(key: 'time_format'); ?>" />
                                </div>
                                <?php Action::getInstance()->doAction('options_reading_form'); ?>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.left column -->

                </div>
                <!--/.row -->
            </section>
            <!-- /.Main content -->
        </div>
    </form>
    <!-- /.Content Wrapper. Contains post content -->
<?php }); ?>
