<?php

declare(strict_types=1);

/**
 * System Snapshot Report View
 */

use App\Application\Devflow;
use App\Infrastructure\Services\Options;
use App\Shared\Services\Registry;
use Qubus\EventDispatcher\ActionFilter\Action;

use function App\Shared\Helpers\convert_seconds_to_time;
use function App\Shared\Helpers\is_multisite;
use function App\Shared\Helpers\site_url;
use function Codefy\Framework\Helpers\base_path;
use function Codefy\Framework\Helpers\config;
use function Codefy\Framework\Helpers\storage_path;
use function Qubus\Security\Helpers\esc_html;
use function Qubus\Security\Helpers\esc_html__;

$this->parent('framework::backend/layouts/admin-layout');
$this->block('backend', function ($params) {
Registry::getInstance()->{'set'}('screen_parent', 'dashboard');
Registry::getInstance()->{'set'}('screen_child', 'snapshot');
$option = Options::factory();
?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="box box-solid">
            <div class="box-header with-border">
                <i class="fa fa-file-image-o"></i>
                <h3 class="box-title"><?= esc_html__(string: 'System Report', domain: 'devflow'); ?></h3>
            </div>
        </div>

        <!-- Main content -->
        <section class="content">

            <?php Action::getInstance()->doAction('admin_notices'); ?>

            <?= Devflow::inst()::$APP->flash->display(); ?>

            <div class="box box-default">
            <pre>
                <?php

                $report = "\n\t" . esc_html(string: '** DATA **'). PHP_EOL . PHP_EOL;
                $report .= esc_html(string: 'Site URL:'). "\t\t\t\t\t\t" . site_url() . PHP_EOL;
                $report .= esc_html(string: 'Devflow Release:'). "\t\t\t\t\t" . Devflow::inst()->release() . PHP_EOL;
                $report .= esc_html(string: 'API Key:'). "\t\t\t\t\t\t" . (preg_match('/\s/', $option->read('api_key')) ? '<span style="color: red; ">' . esc_html(string: 'No'). '</span>': '<span style="color: green; ">' . esc_html(string: 'Yes'). '</span>') . PHP_EOL;
                $report .= esc_html(string: 'Active User Count:'). "\t\t\t\t\t" . $params['users'] . PHP_EOL;

                $report .= "\n\t" . esc_html(string: '** CONFIG **'). PHP_EOL . PHP_EOL;
                $report .= esc_html(string: 'Environment:'). "\t\t\t\t\t\t" . (config(key: 'app.env') === 'prod' ? '<span style="color: green; ">' . esc_html(string: 'Production'). '</span>': '<span style="color: red; ">' . esc_html(string: 'Development'). '</span>') . PHP_EOL;
                $report .= esc_html(string: 'Base Path:'). "\t\t\t\t\t\t" . base_path() . PHP_EOL;
                $report .= esc_html(string: 'Multisite:'). "\t\t\t\t\t\t" . (is_multisite() ? '<span style="color: green; ">' . esc_html(string: 'Enabled'). '</span>': '<span style="color: red; ">' . esc_html(string: 'Disabled'). '</span>') . PHP_EOL;

                $report .= "\n\t" . esc_html(string: '** SERVER DATA **'). PHP_EOL . PHP_EOL;
                $report .= esc_html(string: 'PHP Version:'). "\t\t\t\t\t\t" . PHP_VERSION . PHP_EOL;
                $report .= esc_html(string: 'PHP Handler:'). "\t\t\t\t\t\t" . PHP_SAPI . PHP_EOL;
                $report .= esc_html(string: 'Server Software:'). "\t\t\t\t\t" . $_SERVER['SERVER_SOFTWARE'] . PHP_EOL;

                $report .= "\n\t" . esc_html(string: '** PHP CONFIGURATION **'). PHP_EOL . PHP_EOL;
                $report .= esc_html(string: 'Memory Limit:'). "\t\t\t\t\t\t" . ini_get('memory_limit') . PHP_EOL;
                $report .= esc_html(string: 'Upload Max Size:'). "\t\t\t\t\t" . ini_get('upload_max_filesize') . PHP_EOL;
                $report .= esc_html(string: 'Post Max Size:'). "\t\t\t\t\t\t" . ini_get('post_max_size') . PHP_EOL;
                $report .= esc_html(string: 'Max Execution Time:'). "\t\t\t\t\t" . ini_get('max_execution_time') . PHP_EOL;
                $report .= esc_html(string: 'Max Input Vars:'). "\t\t\t\t\t\t" . ini_get('max_input_vars') . PHP_EOL;
                $report .= esc_html(string: 'Cookie Path:'). "\t\t\t\t\t\t" . (is_writable(storage_path('app/cookies')) ? '<span style="color: green; ">' . storage_path('app/cookies') . '</span>': '<span style="color: red; ">' . storage_path('app/cookies') . '</span>') . PHP_EOL;
                $report .= esc_html(string: 'Regular Cookie TTL:'). "\t\t\t\t\t" . convert_seconds_to_time((int) config('cookies.lifetime')) . PHP_EOL;
                $report .= esc_html(string: 'Secure Cookie TTL:'). "\t\t\t\t\t" . convert_seconds_to_time((int) $option->read('cookieexpire')) . PHP_EOL;
                $report .= esc_html(string: 'cURL Enabled:'). "\t\t\t\t\t\t" . (function_exists('curl_version') ? '<span style="color: green; ">' . esc_html(string: 'Yes'). '</span>': '<span style="color: red; ">' . esc_html(string: 'No'). '</span>') . PHP_EOL;
                // end it all
                $report .= PHP_EOL;

                echo $report;

                ?>
            </pre>
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
<?php }); ?>