<?php

use App\Application\Devflow;
use App\Domain\ContentType\ValueObject\ContentTypeId;
use App\Shared\Services\Registry;
use Qubus\EventDispatcher\ActionFilter\Action;

use function App\Shared\Helpers\admin_url;
use function App\Shared\Helpers\ae;
use function App\Shared\Helpers\number_content_by_type;
use function Codefy\Framework\Helpers\trans_html;

$this->parent('framework::backend/layouts/admin-layout');
$this->block('backend', function ($params) {
Registry::getInstance()->{'set'}('screen_parent', 'content_types');
?>

    <script src="static/assets/js/url_slug.js" type="text/javascript"></script>
    <script>
        $(function(){
            $('#type_title').keyup(function() {
                $('#type_slug').val(url_slug($(this).val()));
            });
        });
    </script>

    <!-- form start -->
    <form name="form" method="post" data-toggle="validator" action="<?= admin_url('content-type/create/'); ?>" autocomplete="off">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="box box-solid">
                <div class="box-header with-border">
                    <i class="fa fa-thumb-tack"></i>
                    <h3 class="box-title"><?= trans_html(string: 'Content Types'); ?></h3>

                    <div class="pull-right">
                        <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> <?= trans_html(string: 'Save'); ?></button>
                        <input type="hidden" name="id" value="<?=ContentTypeId::generateAsString();?>">
                    </div>
                </div>
            </div>

            <!-- Main content -->
            <section class="content">

                <?php Action::getInstance()->doAction('admin_notices'); ?>

                <?= Devflow::$PHP->flash->display(); ?>

                <div class="row">
                    <!-- left column -->
                    <div class="col-md-4">
                        <!-- general form elements -->
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?=trans_html(string: 'Add New Content Type');?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?=trans_html(string: 'Content Type Name');?></strong></label>
                                    <input type="text" class="form-control input-lg" name="title" id="type_title" value="<?= $params['request']['title'] ?? ''; ?>" required/>
                                </div>
                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?=trans_html(string: 'Content Type Slug');?></strong> <a href="#slug" data-toggle="modal"><span class="badge"><i class="fa fa-question"></i></span></a></label>
                                    <input type="text" class="form-control" name="slug" id="type_slug" value="<?= $params['request']['slug'] ?? ''; ?>" required/>
                                </div>
                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?=trans_html(string: 'Content Type Description');?></strong></label>
                                    <textarea class="form-control" name="description" required><?= $params['request']['description'] ?? ''; ?></textarea>
                                </div>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.left column -->

                    <!-- right column -->
                    <div class="col-md-8">
                        <!-- general form elements -->
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?=trans_html(string: 'Content Types');?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <table id="example1" class="table table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th class="text-center"><?= trans_html(string: 'Content Type'); ?></th>
                                        <th class="text-center"><?= trans_html(string: 'Description'); ?></th>
                                        <th class="text-center"><?= trans_html(string: 'Slug'); ?></th>
                                        <th class="text-center"><?= trans_html(string: 'Count'); ?></th>
                                        <th class="text-center"><?= trans_html(string: 'Action'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($params['types'] as $contentType) : ?>
                                        <tr class="gradeX">
                                            <td class="text-center"><a href="<?= admin_url('content-type/' . $contentType['id'] . '/'); ?>"><?= $contentType['title']; ?></a></td>
                                            <td class="text-center"><?= $contentType['description']; ?></td>
                                            <td class="text-center"><?= $contentType['slug']; ?></td>
                                            <td class="text-center"><a href="<?= admin_url('content-type' . '/' . $contentType['slug'] . '/'); ?>"><?= number_content_by_type($contentType['slug']); ?></a></td>
                                            <td class="text-center">
                                                <a<?=ae('delete:content');?> href="#" data-toggle="modal" data-target="#delete-<?= $contentType['id']; ?>"><button type="button" class="btn bg-red"><i class="fa fa-trash"></i></button></a>
                                                <div class="modal" id="delete-<?= $contentType['id']; ?>">
                                                    <div class="modal-dialog">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span></button>
                                                                <h4 class="modal-title"><?= $contentType['title']; ?></h4>
                                                            </div>
                                                            <div class="modal-body">
                                                                <p><?=trans_html(string: 'Are you sure you want to delete this content type? By deleting this content type, you also delete all content connected to this content type as well.');?></p>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-default pull-left" data-dismiss="modal"><?= trans_html(string: 'Close'); ?></button>
                                                                <button type="button" class="btn btn-primary" onclick="window.location='<?= admin_url('content-type/' . $contentType['id'] . '/d/'); ?>'"><?= trans_html(string: 'Confirm'); ?></button>
                                                            </div>
                                                        </div>
                                                        <!-- /.modal-content -->
                                                    </div>
                                                    <!-- /.modal-dialog -->
                                                </div>
                                                <!-- /.modal -->
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th class="text-center"><?= trans_html(string: 'Content Type'); ?></th>
                                        <th class="text-center"><?= trans_html(string: 'Description'); ?></th>
                                        <th class="text-center"><?= trans_html(string: 'Slug'); ?></th>
                                        <th class="text-center"><?= trans_html(string: 'Count'); ?></th>
                                        <th class="text-center"><?= trans_html(string: 'Action'); ?></th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box-primary -->
                    </div>
                    <!-- /.right column -->

                </div>
                <!--/.row -->
            </section>
            <!-- /.Main content -->

            <!-- modal -->
            <div class="modal" id="slug">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title"><?=trans_html(string: 'Content Type Slug');?></h4>
                        </div>
                        <div class="modal-body">
                            <p><?=trans_html(string: "If left blank, the system will auto generate the content type slug.");?></p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default pull-left" data-dismiss="modal"><?= trans_html(string: 'Close'); ?></button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->

        </div>
    </form>
    <!-- /.Content Wrapper. Contains page content -->
<?php }); ?>
