<?php

declare(strict_types=1);

use App\Application\Devflow;
use App\Shared\Services\Registry;
use Qubus\EventDispatcher\ActionFilter\Action;

use function App\Shared\Helpers\admin_url;
use function Qubus\Security\Helpers\esc_html__;

$this->parent('framework::backend/layouts/admin-layout');
$this->block('backend', function ($params) {
Registry::getInstance()->{'set'}('screen_parent', 'content_types');
?>

    <script src="static/assets/js/url_slug.js" type="text/javascript"></script>
    <script>
        $(function(){
            $('#type_title').keyup(function() {
                $('#type_slug').val(url_slug($(this).val()));
            });
        });
    </script>

    <!-- form start -->
    <form method="post" action="<?=admin_url('content-type/' . $params['type']->id . '/'); ?>" data-toggle="validator" autocomplete="off">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="box box-solid">
                <div class="box-header with-border">
                    <i class="fa fa-thumb-tack"></i>
                    <h3 class="box-title"><?= esc_html__(string: 'Update Content Type', domain: 'devflow'); ?></h3>

                    <div class="pull-right">
                        <input type="hidden" class="form-control" name="id" id="id" value="<?=$params['type']->id;?>" required/>
                        <button type="submit" class="btn btn-success"><i class="fa fa-pencil-alt"></i> <?= esc_html__(string: 'Update', domain: 'devflow'); ?></button>
                        <button type="button" class="btn btn-primary" onclick="window.location='<?=admin_url('content-type/');?>'"><i class="fa fa-ban"></i> <?= esc_html__(string: 'Cancel', domain: 'devflow'); ?></button>
                    </div>
                </div>
            </div>

            <!-- Main content -->
            <section class="content">

                <?php Action::getInstance()->doAction('admin_notices'); ?>

                <?= Devflow::$PHP->flash->display(); ?>

                <div class="box box-default">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= esc_html__(string: 'Content Type Name', domain: 'devflow'); ?></strong></label>
                                    <input type="text" class="form-control input-lg" name="title" id="type_title" value="<?=$params['type']->title;?>" required/>
                                </div>
                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= esc_html__(string: 'Content Type Slug', domain: 'devflow'); ?></strong></label>
                                    <input type="text" class="form-control" name="slug" id="type_slug" value="<?=$params['type']->slug;?>" required/>
                                </div>

                                <div class="form-group">
                                    <label><strong><span style="color: red; ">*</span> <?= esc_html__(string: 'Content Type Description', domain: 'devflow'); ?></strong> <a href="#slug" data-toggle="modal"><span class="badge"><i class="fa fa-question"></i></span></a></label>
                                    <textarea class="form-control" rows="3" name="description" required><?=$params['type']->description;?></textarea>
                                </div>
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->

            </section>
            <!-- /.content -->

            <!-- modal -->
            <div class="modal" id="slug">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title"><?=esc_html__(string: 'Content Type Slug', domain: 'devflow');?></h4>
                        </div>
                        <div class="modal-body">
                            <p><?=esc_html__(string: "If left blank, the system will auto generate the content type slug.", domain: 'devflow');?></p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default pull-left" data-dismiss="modal"><?= esc_html__(string: 'Close', domain: 'devflow'); ?></button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->

        </div>
        <!-- /.content-wrapper -->
    </form>

<?php }); ?>
