<?php

declare(strict_types=1);

use App\Application\Devflow;
use App\Domain\User\Model\User;
use App\Shared\Services\DateTime;
use Qubus\EventDispatcher\ActionFilter\Action;

use function App\Shared\Helpers\add_dashboard_submenu;
use function App\Shared\Helpers\admin_footer;
use function App\Shared\Helpers\admin_head;
use function App\Shared\Helpers\admin_login_url;
use function App\Shared\Helpers\admin_logout_url;
use function App\Shared\Helpers\admin_url;
use function App\Shared\Helpers\ae;
use function App\Shared\Helpers\cms_release_value;
use function App\Shared\Helpers\current_screen;
use function App\Shared\Helpers\current_user_can;
use function App\Shared\Helpers\get_all_content_types;
use function App\Shared\Helpers\get_current_user_id;
use function App\Shared\Helpers\get_logo_large;
use function App\Shared\Helpers\get_logo_mini;
use function App\Shared\Helpers\get_name;
use function App\Shared\Helpers\get_option;
use function App\Shared\Helpers\get_secure_cookie_data;
use function App\Shared\Helpers\get_theme;
use function App\Shared\Helpers\get_user_avatar;
use function App\Shared\Helpers\get_user_option;
use function App\Shared\Helpers\get_userdata;
use function App\Shared\Helpers\is_main_site;
use function App\Shared\Helpers\is_multisite;
use function App\Shared\Helpers\site_url;
use function Codefy\Framework\Helpers\config;
use function Codefy\Framework\Helpers\trans_html;
use function Qubus\Security\Helpers\esc_attr;
use function Qubus\Security\Helpers\esc_html;

if (isset($_COOKIE['SWITCH_USERBACK'])) :
    $cookie = get_secure_cookie_data(key: 'SWITCH_USERBACK');
endif;
/** @var User $user */
$user = get_userdata(get_current_user_id());
$canInstallPlugins = is_main_site() && current_user_can('install:plugins');
$canInstallThemes = is_main_site() && current_user_can('install:themes');
?>
    <!DOCTYPE html>
    <html lang="<?=Devflow::$PHP->configContainer->string('app.language');?>">
    <head>
        <base href="<?= site_url(); ?>">
        <meta charset="<?=Devflow::$PHP->configContainer->string('app.charset');?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?=$this->esc($title ?? '') . ' &lsaquo; ' . get_option(key: 'sitename'); ?> &#8212; <?=esc_html(string: 'Devflow');?></title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=6, user-scalable=yes" name="viewport">
        <meta name="theme-color" content="#ffffff">
        <link rel="apple-touch-icon" sizes="180x180" href="static/assets/img/apple-touch-icon.png">
        <link rel="icon" type="image/png" href="static/assets/img/favicon-32x32.png" sizes="32x32">
        <link rel="icon" type="image/png" href="static/assets/img/favicon-16x16.png" sizes="16x16">
        <link rel="manifest" href="static/assets/img/manifest.json">
        <link href="static/assets/css/iCheck/all.css" type="text/css" rel="stylesheet" />
        <?php admin_head(); ?>
    </head>
    <body class="hold-transition <?= get_user_option('admin.skin', $user->id) ?: 'skin-red'; ?> <?= (get_user_option('admin.layout', $user->id) === 0 ? 'fixed ' : ''); ?><?= (get_user_option('admin.sidebar', $user->id) === 0 ? 'sidebar-collapse ' : ''); ?>sidebar-mini">
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a href="<?= admin_url(); ?>" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini" style="font-size: .65em;"><?= get_logo_mini(); ?></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><?= get_logo_large(); ?></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top default-navbar">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                  <span class="sr-only"><?=trans_html(string: 'Toggle navigation');?></span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <?= get_user_avatar($user->email, 160, 'user-image'); ?>
                                <span class="hidden-xs"><?= get_name(get_current_user_id()); ?></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <?= get_user_avatar($user->email, 160, 'image-circle'); ?>

                                    <p>
                                        <?= get_name(get_current_user_id()); ?>
                                        <small><?=trans_html(string: 'Member since'); ?> <?= new DateTime()->db2date('M Y', $user->registered); ?></small>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <?php if(null !== get_user_option('role', $user->id)) : ?>
                                        <a<?= ae('manage:profile'); ?> href="<?= admin_url('user/profile/'); ?>" class="btn btn-default btn-flat"><?=trans_html(string: 'Profile');?></a>
                                        <?php endif; ?>
                                    </div>
                                    <?php if (isset($_COOKIE['SWITCH_USERBACK'])) : ?>
                                        <div class="pull-left">
                                            <a href="<?= admin_url(sprintf('user/%s/switch-back/', esc_html($cookie->id))); ?>" class="btn btn-default btn-flat"><?=trans_html(string: 'Switch back');?></a>
                                        </div>
                                    <?php endif; ?>
                                    <div class="pull-right">
                                        <a href="<?=admin_logout_url(admin_login_url());?>" class="btn btn-default btn-flat"><?=trans_html(string: 'Logout');?></a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <!-- Control Sidebar Toggle Button -->
                        <li><p>&nbsp;</p></li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <?= get_user_avatar($user->email, 160, 'img-circle'); ?>
                    </div>
                    <div class="pull-left info">
                        <p><?= get_name(get_current_user_id()); ?></p>
                        <a><i class="fa fa-circle" style="color:#2ecc71"></i> <?=trans_html(string: 'Online');?></a>
                    </div>
                </div>
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="header"><?=trans_html(string: 'MAIN NAVIGATION');?></li>
                    <li class="treeview<?=current_screen('screen_parent', 'dashboard'); ?>">
                        <a href="#">
                            <i class="fa fa-tachometer-alt"></i>
                            <span><?=trans_html(string: 'Dashboard');?></span>
                            <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                        </a>
                        <ul class="treeview-menu">
                            <?= add_dashboard_submenu(trans_html(string: 'Home'), '/', 'home'); ?>
                            <?php if(is_main_site()) : ?>
                            <?= add_dashboard_submenu(trans_html(string: 'Updates'), '/updates/', 'updates', 'core:updates'); ?>
                            <?php endif; ?>
                            <?= add_dashboard_submenu(trans_html(string: 'System Report'), '/snapshot/', 'snapshot', 'manage:settings'); ?>
                            <?php Action::getInstance()->doAction('dashboard_submenu'); ?>
                        </ul>
                    </li>
                    <li<?= ae('manage:settings'); ?> class="treeview">
                        <a href="<?= admin_url('flush-cache/'); ?>">
                            <i class="fa fa-broom"></i> <span><?=trans_html(string: 'Flush Cache');?></span>
                        </a>
                    </li>
                    <?php if(is_multisite() && is_main_site()): ?>
                    <li<?= ae('manage:sites'); ?> class="treeview<?=current_screen('screen_parent', 'sites'); ?>">
                        <a href="#">
                            <i class="fa fa-globe"></i>
                            <span><?=trans_html(string: 'Sites');?></span>
                            <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                        </a>
                        <ul class="treeview-menu">
                            <?= add_dashboard_submenu(trans_html(string: 'Manage'), '/site/', 'sites'); ?>
                            <?= add_dashboard_submenu(trans_html(string: 'Users'), '/site/users/', 'sites-user'); ?>
                            <?php Action::getInstance()->doAction('sites_submenu'); ?>
                        </ul>
                    </li>
                    <?php endif; ?>
                    <li<?= ae('manage:product'); ?> class="treeview<?=current_screen('screen_parent', 'product');?>">
                        <a href="#">
                            <i class="fa fa-archive"></i>
                            <span><?=trans_html(string: 'Products');?></span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <?= add_dashboard_submenu(trans_html(string: 'All Products'), '/product/', 'products'); ?>
                            <?= add_dashboard_submenu(trans_html(string: 'Add New'), '/product/create/', 'product-create'); ?>
                        </ul>
                    </li>
                    <li<?= ae('manage:content'); ?> class="treeview<?=current_screen('screen_parent', 'content_types');?>">
                        <a href="<?= admin_url('content-type/'); ?>">
                            <i class="fa fa-cubes"></i> <span><?=trans_html(string: 'Content Types');?></span>
                        </a>
                    </li>
                    <?php if(count(get_all_content_types()) > 0) : ?>
                    <?php foreach (get_all_content_types() as $contentType) : ?>
                        <li<?= ae('manage:content'); ?> class="treeview<?=current_screen('screen_parent', esc_attr($contentType['slug']));?>">
                            <a href="#">
                                <i class="fa fa-text-width"></i>
                                <span><?= $contentType['title']; ?></span>
                                <span class="pull-right-container">
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </span>
                            </a>
                            <ul class="treeview-menu">
                                <?= add_dashboard_submenu(trans_html(string: 'All') . ' ' . esc_html($contentType['title']), sprintf('/content-type/%s/', $contentType['slug']), $contentType['slug']); ?>
                                <?= add_dashboard_submenu(trans_html(string: 'Add New'), sprintf('/content-type/%s/create/', $contentType['slug']), $contentType['slug'] . '-create'); ?>
                                <?php Action::getInstance()->doAction('content_type_submenu', $contentType['slug']); ?>
                            </ul>
                        </li>
                    <?php endforeach; ?>
                    <?php endif; ?>
                    <?php Action::getInstance()->doAction('content_type_menu'); ?>
                    <li<?= ae('manage:media'); ?> class="treeview<?=current_screen('screen_parent', 'media');?>">
                        <a href="<?= admin_url('media/'); ?>">
                            <i class="fa fa-camera"></i> <span><?=trans_html(string: 'Media Library');?></span>
                        </a>
                    </li>
                    <li<?= ae('manage:plugins'); ?> class="treeview<?=current_screen('screen_parent', 'plugins');?>">
                        <a href="#">
                            <i class="fa fa-plug"></i>
                            <span><?=trans_html(string: 'Plugins');?></span>
                            <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                        </a>
                        <ul class="treeview-menu">
                            <?=add_dashboard_submenu(trans_html(string: 'Installed Plugins'), '/plugin/', 'installed-plugins');?>
                            <?php if($canInstallPlugins) : ?>
                            <?=add_dashboard_submenu(trans_html(string: 'Add Plugin'), '/plugin/install/', 'add-plugin');?>
                            <?php endif; ?>
                            <?php Action::getInstance()->doAction('plugins_submenu'); ?>
                        </ul>
                    </li>
                    <li<?= ae('manage:themes'); ?> class="treeview<?=current_screen('screen_parent', 'themes');?>">
                        <a href="#">
                            <i class="fa fa-palette"></i>
                            <span><?=trans_html(string: 'Themes');?></span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <?=add_dashboard_submenu(trans_html(string: 'Themes'), '/theme/', 'installed-themes');?>
                            <?php if($canInstallThemes) : ?>
                            <?=add_dashboard_submenu(trans_html(string: 'Add Theme'), '/theme/install/', 'add-theme');?>
                            <?php endif; ?>
                            <?php Action::getInstance()->doAction('themes_submenu'); ?>
                        </ul>
                    </li>
                    <?php if(config()->boolean(key: 'vihzhuo.enable') && !empty(get_theme())) : ?>
                    <li<?= ae('vihzhuo:manage'); ?> class="treeview<?=current_screen('screen_parent', 'vihzhuo');?>">
                        <a href="<?= admin_url('manager/'); ?>">
                            <i class="fa fa-layer-group"></i> <span><?=trans_html(string: 'Vihzhuo');?></span>
                        </a>
                    </li>
                    <?php endif; ?>
                    <?php if (current_user_can('manage:users')) : ?>
                        <li class="treeview<?=current_screen('screen_parent', 'users'); ?>">
                            <a href="#">
                                <i class="fa fa-user"></i>
                                <span><?=trans_html(string: 'Users');?></span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <?php Action::getInstance()->doAction('admin_submenu_users'); ?>
                                <?= add_dashboard_submenu(trans_html(string: 'All Users'), '/user/', 'all-users', 'manage:users'); ?>
                                <?= add_dashboard_submenu(trans_html(string: 'Add New'), '/user/create/', 'create-user', 'create:users'); ?>
                                <?= add_dashboard_submenu(trans_html(string: 'Your Profile'), '/user/profile/', 'profile'); ?>
                                <?php Action::getInstance()->doAction('users_submenu'); ?>
                            </ul>
                        </li>
                    <?php else : ?>
                    <?php if(null !== get_user_option('role', $user->id)) : ?>
                        <li<?= ae('manage:profile'); ?> class="treeview<?=current_screen('screen_child', 'profile');?>">
                            <a href="<?= admin_url('user/profile/'); ?>">
                                <i class="fa fa-id-card"></i> <span><?=trans_html(string: 'Your Profile');?></span>
                            </a>
                        </li>
                    <?php endif; ?>
                    <?php endif; ?>
                    <li<?= ae('manage:options'); ?> class="treeview<?=current_screen('screen_parent', 'options');?>">
                        <a href="#">
                            <i class="fa fa-cogs"></i>
                            <span><?=trans_html(string: 'Options');?></span>
                            <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                        </a>
                        <ul class="treeview-menu">
                            <?= add_dashboard_submenu(trans_html(string: 'General'), '/general/', 'options-general'); ?>
                            <?= add_dashboard_submenu(trans_html(string: 'Reading'), '/reading/', 'options-reading'); ?>
                            <?php Action::getInstance()->doAction('options_submenu'); ?>
                        </ul>
                    </li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <?php $this->block('backend'); ?>

        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <div id="remainder"></div>
            </div>
            <?= cms_release_value(); ?>
        </footer>
    </div>
    <!-- ./wrapper -->

    <script>
        var endDate = new Date("<?=new DateTime()->timestampToDate('Y-m-d H:i:s', get_secure_cookie_data(key: 'USERCOOKIEID')->exp);?>").getTime();
        var timer = setInterval(function () {
            let now = new Date().getTime();
            let t = endDate - now;
            if (t >= 0) {
                document.getElementById("remainder").innerHTML =
                    "<?=trans_html('Login expires in ');?>" +
                    Math.floor(t / (1000 * 60 * 60 * 24)) + "day(s) " +
                    ("0" + Math.floor((t % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60))).slice(-2) + "h:" +
                    ("0" + Math.floor((t % (1000 * 60 * 60)) / (1000 * 60))).slice(-2) + "m:" +
                    ("0" + Math.floor((t % (1000 * 60)) / 1000)).slice(-2) + "s";
            } else {
                document.getElementById("remainder").innerHTML = "End of timer.";
            }

        }, 1000);
    </script>
    <script>
        var basePath = '<?= site_url(); ?>';
    </script>

    <?php

    admin_footer();

    /**
     * Fires after Devflow has finished loading.
     */
    Action::getInstance()->doAction('init');
    ?>
    <script>
        let elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
        elems.forEach(function (html) {
            let switchery = new Switchery(html, {size: 'small', secondaryColor: '#ee0000'});
        });
    </script>

    </body>
    </html>
