<?php

declare(strict_types=1);

use App\Domain\User\Model\User;
use App\Infrastructure\Services\Options;
use App\Shared\Services\DateTime;
use Qubus\EventDispatcher\ActionFilter\Action;

use function App\Shared\Helpers\add_dashboard_submenu;
use function App\Shared\Helpers\admin_footer;
use function App\Shared\Helpers\admin_head;
use function App\Shared\Helpers\admin_url;
use function App\Shared\Helpers\ae;
use function App\Shared\Helpers\cms_admin_copyright_footer;
use function App\Shared\Helpers\current_screen;
use function App\Shared\Helpers\current_user_can;
use function App\Shared\Helpers\get_all_content_types;
use function App\Shared\Helpers\get_current_user_id;
use function App\Shared\Helpers\get_logo_large;
use function App\Shared\Helpers\get_logo_mini;
use function App\Shared\Helpers\get_name;
use function App\Shared\Helpers\get_secure_cookie_data;
use function App\Shared\Helpers\get_user_avatar;
use function App\Shared\Helpers\get_user_option;
use function App\Shared\Helpers\get_userdata;
use function App\Shared\Helpers\is_multisite;
use function App\Shared\Helpers\site_url;
use function Qubus\Security\Helpers\esc_attr;
use function Qubus\Security\Helpers\esc_html;
use function Qubus\Security\Helpers\esc_html__;

if (isset($_COOKIE['SWITCH_USERBACK'])) :
    $cookie = get_secure_cookie_data(key: 'SWITCH_USERBACK');
endif;
/** @var User $user */
$user = get_userdata(get_current_user_id());
$option = Options::factory();
?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <base href="<?= site_url(); ?>">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?=$this->esc($title ?? '') . ' &lsaquo; ' . $option->{'read'}('sitename'); ?> &#8212; <?=esc_html(string: 'Devflow');?></title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=6, user-scalable=yes" name="viewport">
        <meta name="theme-color" content="#ffffff">
        <!-- Bootstrap 3.4.1 -->
        <link rel="stylesheet" href="static/assets/css/bootstrap/lumen-bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/ionicons/4.5.6/css/ionicons.min.css">
        <!-- Favicon Package -->
        <link rel="apple-touch-icon" sizes="180x180" href="static/assets/img/apple-touch-icon.png">
        <link rel="icon" type="image/png" href="static/assets/img/favicon-32x32.png" sizes="32x32">
        <link rel="icon" type="image/png" href="static/assets/img/favicon-16x16.png" sizes="16x16">
        <link rel="manifest" href="static/assets/img/manifest.json">
        <!-- jQuery 2.2.4 -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jQuery-slimScroll/1.3.8/jquery.slimscroll.min.js"></script>
        <!-- jQuery UI 1.12.1 -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
        <link href="static/assets/css/datatables/dataTables.bootstrap.css" type="text/css" rel="stylesheet" />
        <link href="static/assets/css/select2/select2.min.css" type="text/css" rel="stylesheet" />
        <link href="static/assets/css/iCheck/all.css" type="text/css" rel="stylesheet" />
        <link href="//gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
        <link href="static/assets/css/bootstrap-datetimepicker/bootstrap-datetimepicker.min.css" type="text/css" rel="stylesheet" />
        <link href="static/assets/css/bootstrap-switchery/switchery.min.css" type="text/css" rel="stylesheet" />
        <!-- Theme style -->
        <link rel="stylesheet" href="static/assets/css/AdminLTE.min.css">
        <!-- AdminLTE Skins. Choose a skin from the css/skins
             folder instead of downloading all of them to reduce the load. -->
        <link rel="stylesheet" href="static/assets/css/skins/_all-skins.min.css">
        <?php admin_head(); ?>
    </head>
    <body class="hold-transition <?= get_user_option('admin_skin', $user->id); ?> <?= (get_user_option('admin_layout', $user->id) === '0' ? 'fixed ' : ''); ?><?= (get_user_option('admin_sidebar', $user->id) === '0' ? 'sidebar-collapse ' : ''); ?>sidebar-mini">
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a href="<?= admin_url(); ?>" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini" style="font-size: .65em;"><?= get_logo_mini(); ?></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><?= get_logo_large(); ?></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top default-navbar">
                <!-- Sidebar toggle button-->
                <!--<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                      <span class="sr-only"><?=esc_html__(string: 'Toggle navigation', domain: 'devflow');?></span>
                    </a>-->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <?= get_user_avatar($user->email, 160, 'user-image'); ?>
                                <span class="hidden-xs"><?= get_name(get_current_user_id()); ?></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <?= get_user_avatar($user->email, 160, 'image-circle'); ?>

                                    <p>
                                        <?= get_name(get_current_user_id()); ?>
                                        <small><?=esc_html__(string: 'Member since', domain: 'devflow'); ?> <?= (new DateTime())->db2date('M Y', $user->registered); ?></small>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="<?= admin_url('user/profile/'); ?>" class="btn btn-default btn-flat"><?=esc_html__(string: 'Profile', domain: 'devflow');?></a>
                                    </div>
                                    <?php if (isset($_COOKIE['SWITCH_USERBACK'])) : ?>
                                        <div class="pull-left">
                                            <a href="<?= admin_url('user/' . $cookie->id . '/switch-back/'); ?>" class="btn btn-default btn-flat"><?=esc_html__(string: 'Switch back', domain: 'devflow');?></a>
                                        </div>
                                    <?php endif; ?>
                                    <div class="pull-right">
                                        <a href="<?= admin_url('logout/'); ?>?redirect_to=<?=admin_url('login/');?>" class="btn btn-default btn-flat"><?=esc_html__(string: 'Logout', domain: 'devflow');?></a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <!-- Control Sidebar Toggle Button -->
                        <li><p>&nbsp;</p></li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <?= get_user_avatar($user->email, 160, 'img-circle'); ?>
                    </div>
                    <div class="pull-left info">
                        <p><?= get_name(get_current_user_id()); ?></p>
                        <a><i class="fa fa-circle" style="color:#2ecc71"></i> <?=esc_html__(string: 'Online', domain: 'devflow');?></a>
                    </div>
                </div>
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="header"><?=esc_html__(string: 'MAIN NAVIGATION', domain: 'devflow');?></li>
                    <li class="treeview<?=current_screen('screen_parent', 'dashboard'); ?>">
                        <a href="#">
                            <i class="fa fa-tachometer-alt"></i>
                            <span><?=esc_html__(string: 'Dashboard', domain: 'devflow');?></span>
                            <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                        </a>
                        <ul class="treeview-menu">
                            <?= add_dashboard_submenu(esc_html__(string: 'Home', domain: 'devflow'), '/', 'home'); ?>
                            <?= add_dashboard_submenu(esc_html__(string: 'System Report', domain: 'devflow'), '/snapshot/', 'snapshot', 'manage:settings'); ?>
                            <?php Action::getInstance()->doAction('dashboard_submenu'); ?>
                        </ul>
                    </li>
                    <li<?= ae('manage:settings'); ?> class="treeview">
                        <a href="<?= admin_url('flush-cache/'); ?>">
                            <i class="fa fa-broom"></i> <span><?=esc_html__(string: 'Flush Cache', domain: 'devflow');?></span>
                        </a>
                    </li>
                    <?php if(is_multisite()) : ?>
                    <li<?= ae('manage:sites'); ?> class="treeview<?=current_screen('screen_parent', 'sites'); ?>">
                        <a href="#">
                            <i class="fa fa-globe"></i>
                            <span><?=esc_html__(string: 'Sites', domain: 'devflow');?></span>
                            <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                        </a>
                        <ul class="treeview-menu">
                            <?= add_dashboard_submenu(esc_html__(string: 'Manage', domain: 'devflow'), '/site/', 'sites'); ?>
                            <?= add_dashboard_submenu(esc_html__(string: 'Users', domain: 'devflow'), '/site/users/', 'sites-user'); ?>
                            <?php Action::getInstance()->doAction('sites_submenu'); ?>
                        </ul>
                    </li>
                    <?php endif; ?>
                    <li<?= ae('manage:product'); ?> class="treeview<?=current_screen('screen_parent', 'product');?>">
                        <a href="#">
                            <i class="fa fa-archive"></i>
                            <span><?=esc_html__(string: 'Products', domain: 'devflow');?></span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <?= add_dashboard_submenu(esc_html__(string: 'All Products', domain: 'devflow'), '/product/', 'products'); ?>
                            <?= add_dashboard_submenu(esc_html__(string: 'Add New', domain: 'devflow'), '/product/create/', 'product-create'); ?>
                        </ul>
                    </li>
                    <li<?= ae('manage:content'); ?> class="treeview<?=current_screen('screen_parent', 'content_types');?>">
                        <a href="<?= admin_url('content-type/'); ?>">
                            <i class="fa fa-cubes"></i> <span><?=esc_html__(string: 'Content Types', domain: 'devflow');?></span>
                        </a>
                    </li>
                    <?php if(count(get_all_content_types()) > 0) : ?>
                    <?php foreach (get_all_content_types() as $contentType) : ?>
                        <li<?= ae('manage:content'); ?> class="treeview<?=current_screen('screen_parent', esc_attr($contentType['slug']));?>">
                            <a href="#">
                                <i class="fa fa-text-width"></i>
                                <span><?= $contentType['title']; ?></span>
                                <span class="pull-right-container">
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </span>
                            </a>
                            <ul class="treeview-menu">
                                <?= add_dashboard_submenu(esc_html__(string: 'All', domain: 'devflow') . ' ' . esc_html($contentType['title']), '/content-type/' . $contentType['slug'] . '/', $contentType['slug']); ?>
                                <?= add_dashboard_submenu(esc_html__(string: 'Add New', domain: 'devflow'), '/content-type/' . $contentType['slug'] . '/create/', $contentType['slug'] . '-create'); ?>
                                <?php Action::getInstance()->doAction('content_type_submenu', $contentType['slug']); ?>
                            </ul>
                        </li>
                    <?php endforeach; ?>
                    <?php endif; ?>
                    <?php Action::getInstance()->doAction('content_type_menu'); ?>
                    <li<?= ae('manage:media'); ?> class="treeview<?=current_screen('screen_parent', 'media');?>">
                        <a href="<?= admin_url('media/'); ?>">
                            <i class="fa fa-camera"></i> <span><?=esc_html__(string: 'Media Library', domain: 'devflow');?></span>
                        </a>
                    </li>
                    <li<?= ae('manage:plugins'); ?> class="treeview<?=current_screen('screen_parent', 'plugins');?>">
                        <a href="#">
                            <i class="fa fa-plug"></i>
                            <span><?=esc_html__(string: 'Plugins', domain: 'devflow');?></span>
                            <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                        </a>
                        <ul class="treeview-menu">
                            <?=add_dashboard_submenu(esc_html__(string: 'Plugins', domain: 'devflow'), '/plugin/', 'installed-plugins');?>
                            <?php Action::getInstance()->doAction('plugins_submenu'); ?>
                        </ul>
                    </li>
                    <?php if (current_user_can('manage:users')) : ?>
                        <li class="treeview<?=current_screen('screen_parent', 'users'); ?>">
                            <a href="#">
                                <i class="fa fa-user"></i>
                                <span><?=esc_html__(string: 'Users', domain: 'devflow');?></span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <?php Action::getInstance()->doAction('admin_submenu_users'); ?>
                                <?= add_dashboard_submenu(esc_html__(string: 'All Users', domain: 'devflow'), '/user/', 'all-users', 'manage:users'); ?>
                                <?= add_dashboard_submenu(esc_html__(string: 'Add New', domain: 'devflow'), '/user/create/', 'create-user', 'create:users'); ?>
                                <?= add_dashboard_submenu(esc_html__(string: 'Your Profile', domain: 'devflow'), '/user/profile/', 'profile'); ?>
                                <?php Action::getInstance()->doAction('users_submenu'); ?>
                            </ul>
                        </li>
                    <?php else : ?>
                        <li>
                            <a href="<?= admin_url('user/profile/'); ?>">
                                <i class="fa fa-id-card"></i> <span><?=esc_html__(string: 'Your Profile', domain: 'devflow');?></span>
                            </a>
                        </li>
                    <?php endif; ?>
                    <li<?= ae('manage:options'); ?> class="treeview<?=current_screen('screen_parent', 'options');?>">
                        <a href="#">
                            <i class="fa fa-cogs"></i>
                            <span><?=esc_html__(string: 'Options', domain: 'devflow');?></span>
                            <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                        </a>
                        <ul class="treeview-menu">
                            <?= add_dashboard_submenu(esc_html__(string: 'General', domain: 'devflow'), '/general/', 'options-general'); ?>
                            <?= add_dashboard_submenu(esc_html__(string: 'Reading', domain: 'devflow'), '/reading/', 'options-reading'); ?>
                            <?php Action::getInstance()->doAction('options_submenu'); ?>
                        </ul>
                    </li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <?php $this->block('backend'); ?>

        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <?php //cms_release(); ?>
            </div>
            <?= cms_admin_copyright_footer(); ?>
        </footer>
    </div>
    <!-- ./wrapper -->

    <script>
        var basePath = '<?= site_url(); ?>';
    </script>
    <!-- Bootstrap 3.3.6 -->
    <script src="static/assets/js/bootstrap/bootstrap.min.js"></script>
    <!-- Bootstrap Validator 0.11.7 -->
    <script src="static/assets/plugins/bootstrap-validator/validator.js"></script>
    <!-- AdminLTE App -->
    <script src="static/assets/js/app.min.js"></script>
    <!-- Switchery -->
    <script src="static/assets/js/bootstrap-switchery/switchery.min.js"></script>
    <script src="static/assets/js/select2/select2.full.min.js" type="text/javascript"></script>
    <script src="static/assets/js/pages/select2.js" type="text/javascript"></script>
    <script src="static/assets/js/daterangepicker/moment.min.js" type="text/javascript"></script>
    <script src="static/assets/js/bootstrap-datetimepicker/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
    <script src="static/assets/js/pages/datetime.js" type="text/javascript"></script>
    <script src="static/assets/js/iCheck/icheck.min.js" type="text/javascript"></script>
    <script src="static/assets/js/pages/iCheck.js" type="text/javascript"></script>
    <script src="//gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <script src="static/assets/js/demo.js"></script>
    <script src="static/assets/js/datatables/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="static/assets/js/datatables/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <script src="static/assets/js/pages/datatable.js" type="text/javascript"></script>
    <script>
        let elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
        elems.forEach(function (html) {
            let switchery = new Switchery(html, {size: 'small', secondaryColor: '#ee0000'});
        });
    </script>

    <?php

    admin_footer();

    /**
     * Fires after Devflow has finished loading.
     */
    Action::getInstance()->doAction('init');
    ?>

    </body>
    </html>