<?php

declare(strict_types=1);

use App\Application\Devflow;
use App\Infrastructure\Services\Options;

use function App\Shared\Helpers\site_url;
use function Qubus\Security\Helpers\esc_html__;
use function Qubus\Security\Helpers\t__;

$option = Options::factory();
?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <base href="<?= site_url(); ?>">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
        <title><?= t__(msgid: 'Login', domain: 'devflow') . ' &lsaquo; ' . $option->{'read'}('sitename'); ?> &#8212; <?= t__(msgid: 'Devflow', domain: 'devflow'); ?></title>
        <link rel="stylesheet" href="static/assets/css/auth/bootstrap.min.css">
        <link rel="stylesheet" href="static/assets/css/auth/auth.min.css">
        <!-- Favicon Package -->
        <link rel="apple-touch-icon" sizes="180x180" href="static/assets/img/apple-touch-icon.png">
        <link rel="icon" type="image/png" href="static/assets/img/favicon-32x32.png" sizes="32x32">
        <link rel="icon" type="image/png" href="static/assets/img/favicon-16x16.png" sizes="16x16">
        <link rel="manifest" href="static/assets/img/manifest.json">
    </head>

    <body class="my-login-page">
    <section class="h-100">
        <div class="container h-100">
            <div class="row justify-content-md-center h-100">
                <div class="card-wrapper">

                    <?php $this->block('auth'); ?>

                    <div class="footer">
                        <footer>
                            <div class="container">
                                <div class="col-md-12 col-md-offset-1 text-center">
                                    <h6 style="font-size:14px;font-weight:400;"><?= esc_html__(string: 'Powered by', domain: 'devflow'); ?> <a href="//getdevflow.com"><?= esc_html__(string: 'Devflow', domain: 'devflow'); ?></a> r<?=Devflow::inst()->release();?></h6>
                                </div>
                            </div>
                        </footer>
                    </div>

                </div>
            </div>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="static/assets/js/auth/auth.min.js"></script>
    </body>
    </html>