<?php

use App\Application\Devflow;
use App\Shared\Services\Registry;

use function App\Shared\Helpers\admin_url;
use function App\Shared\Helpers\ae;
use function App\Shared\Helpers\is_plugin_activated;
use function App\Shared\Helpers\plugin_info;
use function Codefy\Framework\Helpers\public_path;
use function Qubus\Security\Helpers\esc_attr__;
use function Qubus\Security\Helpers\esc_html__;
use function Qubus\Security\Helpers\esc_url;

$this->parent('framework::backend/layouts/admin-layout');
$this->block('backend', function ($params) {
Registry::getInstance()->{'set'}('screen_parent', 'vihzhuo');
Registry::getInstance()->{'set'}('screen_child', 'vihzhuo-index');

$setting = phpb_instance('setting');
?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="box box-solid">
            <div class="box-header with-border">
                <i class="fa fa-layer-group"></i>
                <h3 class="box-title"><?= esc_html__('Page Builder'); ?></h3>

                <div class="pull-right">
                    <a href="<?=phpb_url('website_manager', ['route' => 'page_settings', 'action' => 'create']);?>">
                        <button type="button" class="btn btn-warning"><?=phpb_trans('website-manager.add-new-page');?></button>
                    </a>
                </div>
            </div>
        </div>

        <!-- Main content -->
        <section class="content">

            <?=Devflow::$PHP->flash->display(); ?>

            <div class="row">
                <!-- left column -->
                <div class="col-md-9">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title"><?=esc_html__('Pages');?></h3>
                        </div>

                        <!-- /.box-header -->
                        <div class="box-body">
                            <table class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th class="text-center"><?=phpb_trans('website-manager.name');?></th>
                                    <th class="text-center"><?=phpb_trans('website-manager.route');?></th>
                                    <th class="text-center"><?=phpb_trans('website-manager.actions');?></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($params['pages'] as $page): ?>
                                <tr class="gradeX">
                                    <td class="text-center"><?=phpb_e($page->getName());?></td>
                                    <td class="text-center"><?=phpb_e($page->getRoute());?></td>
                                    <td class="text-center">
                                        <a href="<?=phpb_e(phpb_full_url($page->getRoute()));?>" data-toggle="tooltip" data-placement="top" title="<?=phpb_trans('website-manager.view');?>"><button type="button" class="btn bg-yellow"><i class="fa fa-eye"></i></button></a>
                                        <a href="<?=phpb_url('pagebuilder', ['page' => $page->getId()]);?>" data-toggle="tooltip" data-placement="top" title="<?=phpb_trans('website-manager.edit');?>"><button type="button" class="btn bg-purple"><i class="fa fa-edit"></i></button></a>
                                        <a href="<?=phpb_url('website_manager', ['route' => 'page_settings', 'action' => 'edit', 'page' => $page->getId()]);?>" data-toggle="tooltip" data-placement="top" title="<?=phpb_trans('website-manager.settings');?>"><button type="button" class="btn bg-blue"><i class="fa fa-cog"></i></button></a>
                                        <a href="#" data-toggle="modal" data-target="#delete-<?=$page->getId();?>"><button type="button" class="btn bg-red"><i class="fa fa-trash"></i></button></a>
                                        <div class="modal" id="delete-<?=$page->getId();?>">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span></button>
                                                        <h4 class="modal-title"><?=$page->getName();?></h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p><?= esc_html__(string: 'Are you sure you want to delete this page?', domain: 'devflow'); ?></p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-default pull-left" data-dismiss="modal"><?= esc_html__(string: 'Cancel', domain: 'devflow'); ?></button>
                                                        <a href="<?=phpb_url('website_manager', ['route' => 'page_settings', 'action' => 'destroy', 'page' => $page->getId()]);?>"><button type="button" class="btn btn-primary"><?= esc_html__(string: 'Confirm', domain: 'devflow'); ?></button></a>
                                                    </div>
                                                </div>
                                                <!-- /.modal-content -->
                                            </div>
                                            <!-- /.modal-dialog -->
                                        </div>
                                        <!-- /.modal -->
                                    </td>
                                    <?php endforeach; ?>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th class="text-center"><?=phpb_trans('website-manager.name');?></th>
                                    <th class="text-center"><?=phpb_trans('website-manager.route');?></th>
                                    <th class="text-center"><?=phpb_trans('website-manager.actions');?></th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box-primary -->
                </div>
                <!-- /.left column -->

                <!-- left column -->
                <div class="col-md-3">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title"><?=esc_html__('Languages');?></h3>
                        </div>

                        <div class="box-body">
                            <form method="post" action="<?=phpb_url('website_manager', ['route' => 'settings', 'action' => 'update', 'tab' => 'settings']);?>">
                                <div class="form-group mb-4 mt-6">
                                    <label for="languages" class="mb-2">
                                        <?=phpb_trans('website-manager.website-languages');?>
                                        <span class="text-muted">(<?=esc_html__(string: 'Use Ctrl/Cmd to select multiple.', domain: 'devflow');?>)</span>
                                    </label>
                                    <select class="form-control" id="languages" name="languages[]" title="<?=phpb_trans('website-manager.languages-selector-placeholder');?>" required multiple>
                                        <?php
                                        foreach (phpb_trans('languages') as $locale => $localeText):
                                            ?>
                                            <option value="<?=phpb_e($locale);?>" <?= phpb_e($setting::has('languages', $locale)) !== '' && phpb_e($setting::has('languages', $locale)) !== '0' ? 'selected' : '' ?>><?= phpb_e($localeText) ?></option>
                                        <?php
                                        endforeach;
                                        ?>
                                    </select>
                                </div>

                                <hr class="mb-4">

                                <button class="btn btn-success">
                                    <?=phpb_trans('website-manager.save-settings');?>
                                </button>

                            </form>
                        </div>
                    </div>
                </div>

            </div>
            <!--/.row -->
        </section>
        <!-- /.Main content -->

    </div>
    <!-- /.Content Wrapper. Contains page content -->
<?php }); ?>
