<?php

return [
    /** Named or grouped permissions. */
    'permissions' => [
        'system' => [
            'description' => 'System permissions',
            'permissions' => [
                'access:admin' => ['description' => 'Access to the dashboard.'],
                'manage:media' => ['description' => 'Manage media.'],
                'manage:settings' => ['description' => 'Manage settings.'],
                'change:settings' => ['description' => 'Update or delete settings.'],
                'manage:options' => ['description' => 'Manage plugin or theme options.'],
                'change:options' => ['description' => 'Update or delete plugin or theme options.'],
                'manage:profile' => ['description' => 'User can manage their profile.'],
                'core:updates' => ['description' => 'Manage system updates.'],
                'flush:cache' => ['description' => 'Flush the cache.'],
                'change:username' => ['description' => 'Update a user username.'],
                'reset:password' => ['description' => 'Can reset a user password.'],
            ],
        ],
        'content' => [
            'description' => 'Content permissions',
            'permissions' => [
                'create:content' => ['description' => 'Create content.'],
                'manage:content' => ['description' => 'Manage content.'],
                'update:content' => ['description' => 'Update content.'],
                'delete:content' => ['description' => 'Delete content.'],
                'publish:content' => ['description' => 'Publish content.'],
                'schedule:content' => ['description' => 'Schedule content for publishing.'],
                'archive:content' => ['description' => 'Archive content.'],
                'review:content' => ['description' => 'Review content for publishing.'],
                'assign:content_reviewers' => ['description' => 'Assign content to reviewers.'],
                'approve:content' => ['description' => 'Approve content for publishing.'],
                'view:content_revisions' => ['description' => 'View content revisions.'],
                'restore:content_revisions' => ['description' => 'Restore content revisions.'],
                'view:content_activity' => ['description' => 'View content activity.'],
                'manage:content_notifications' => ['description' => 'Manage content notifications.'],
                'view:content_comments' => ['description' => 'View content comments.'],
                'comment:content' => ['description' => 'Manage comments.'],
                'edit:content_comments' => ['description' => 'Edit content comments.'],
                'reply:content_comments' => ['description' => 'Reply to content comments.'],
                'resolve:content_comments' => ['description' => 'Resolve content comments.'],
                'delete:content_comments' => ['description' => 'Delete content comments.'],
            ],
        ],
        'product' => [
            'description' => 'Product permissions',
            'permissions' => [
                'create:product' => ['description' => 'Create product.'],
                'manage:product' => ['description' => 'Manage product.'],
                'manage:products' => ['description' => 'Manage product inventory.'],
                'update:product' => ['description' => 'Update product.'],
                'delete:product' => ['description' => 'Delete product.'],
                'publish:product' => ['description' => 'Publish product.'],
                'review:product' => ['description' => 'Review product for publishing.'],
                'archive:product' => ['description' => 'Archive product.'],
            ],
        ],
        'user' => [
            'description' => 'User permissions',
            'permissions' => [
                'create:users' => ['description' => 'Create users.'],
                'manage:users' => ['description' => 'Manage users.'],
                'update:users' => ['description' => 'Update users.'],
                'delete:users' => ['description' => 'Delete users.'],
                'switch:user' => ['description' => 'Switch user'],
            ],
        ],
        'extensions' => [
            'description' => 'Extension permissions',
            'permissions' => [
                'install:extensions' => ['description' => 'Install any extension.'],
                'uninstall:extensions' => ['description' => 'Uninstall any extension.'],
                'manage:plugins' => ['description' => 'Manage plugins.'],
                'manage:themes' => ['description' => 'Manage themes.'],
                'install:themes' => ['description' => 'Install themes.'],
                'activate:themes' => ['description' => 'Activate themes.'],
                'deactivate:themes' => ['description' => 'Deactivate themes.'],
                'install:plugins' => ['description' => 'Install plugins.'],
                'activate:plugins' => ['description' => 'Activate plugins.'],
                'deactivate:plugins' => ['description' => 'Deactivate plugins.'],
            ],
        ],
        'sites' => [
            'description' => 'All site permissions',
            'permissions' => [
                'manage:sites' => ['description' => 'Manage sites.'],
                'create:sites' => ['description' => 'Create sites.'],
                'update:sites' => ['description' => 'Update sites.'],
                'delete:sites' => ['description' => 'Delete sites.'],
            ]
        ],
        'webmaster' => [
            'description' => 'Website creator and builder.',
            'permissions' => [
                'vihzhuo:manage' => ['description' => 'Can use the Vihzhuo pagebuilder to build pages.'],
            ],
        ],
    ],

    'roles' => [
        'super' => [
            'description' => 'Super administrator',
            'permissions' => ['system','content','product','user','extensions','sites','webmaster'],
        ],
        'admin' => [
            'description' => 'Administrator',
            'permissions' => [
                'access:admin',
                'manage:media',
                'manage:options',
                'change:options',
                'manage:settings',
                'change:settings',
                'manage:profile',
                'flush:cache',
                'change:username',
                'reset:password',
                'content',
                'product',
                'user',
                'extensions',
                'webmaster',
            ],
        ],
        'author' => [
            'description' => 'Author who can create and edit drafts, but cannot publish.',
            'permissions' => [
                'access:admin',
                'manage:content',
                'create:content',
                'update:content',
                'review:content',
                'view:content_activity',
                'view:content_comments',
                'view:content_revisions',
                'comment:content',
                'reply:content_comments',
                'manage:media',
                'manage:profile',
                'flush:cache',
            ],
        ],
        'editor' => [
            'description' => 'Site editor',
            'permissions' => [
                'access:admin',
                'manage:content',
                'update:content',
                'review:content',
                'approve:content',
                'schedule:content',
                'assign:content_reviewers',
                'view:content_activity',
                'view:content_revisions',
                'view:content_comments',
                'comment:content',
                'reply:content_comments',
                'edit:content_comments',
                'resolve:content_comments',
                'manage:product',
                'manage:products',
                'update:product',
                'review:product',
                'manage:media',
                'manage:profile',
                'flush:cache',
            ],
        ],
        'publisher' => [
            'description' => 'Can publish approved content and archive published content.',
            'permissions' => [
                'access:admin',
                'manage:content',
                'update:content',
                'schedule:content',
                'publish:content',
                'archive:content',
                'view:content_activity',
                'view:content_revisions',
                'view:content_comments',
                'comment:content',
                'reply:content_comments',
                'resolve:content_comments',
                'manage:media',
                'manage:profile',
                'flush:cache',
            ],
        ],
        'user' => [],
    ],
];
