<?php

use App\Application\Devflow;

use Qubus\EventDispatcher\ActionFilter\Action;

use function Codefy\Framework\Helpers\site_url;
use function Codefy\Framework\Helpers\trans_html;

?>
<!DOCTYPE html>
<html lang="<?=Devflow::$PHP->configContainer->string('app.language');?>">
<head>
    <base href="<?=site_url()?>">
    <meta charset="<?=Devflow::$PHP->configContainer->string('app.charset');?>">
    <link rel="stylesheet" type="text/css" href="<?=$this->url('static/assets/css/error.css');?>"/>
    <title><?=trans_html('Error 404');?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex,nofollow">
</head>
<body>
<?php Action::getInstance()->doAction('http.404'); ?>
<div class="error-middle">
    <h1><?=trans_html('Error 404 - Not Found');?></h1>
</div>
</body>
</html>
