<?php

use App\Application\Devflow;

use function Codefy\Framework\Helpers\site_url;
use function Qubus\Security\Helpers\t__;

?>
<!DOCTYPE html>
<html lang="<?=Devflow::$PHP->configContainer->string('app.language');?>">
<head>
    <base href="<?=site_url()?>">
    <meta charset="<?=Devflow::$PHP->configContainer->string('app.charset');?>">
    <link rel="stylesheet" type="text/css" href="<?=$this->url('static/assets/css/error.css');?>"/>
    <title><?=t__(msgid: 'Error 404', domain: 'devflow');?></title>
</head>
<body>
<div class="error-middle">
    <h1><?=t__(msgid: 'Error 404 - Not Found', domain: 'devflow');?></h1>
</div>
</body>
</html>
