<?php

use App\Application\Devflow;
use App\Shared\Services\Registry;
use Qubus\EventDispatcher\ActionFilter\Action;

use function App\Shared\Helpers\admin_url;
use function App\Shared\Helpers\ae;
use function App\Shared\Helpers\cms_site_status_label;
use function App\Shared\Helpers\get_name;
use function App\Shared\Helpers\get_users_dropdown_list;
use function Codefy\Framework\Helpers\config;
use function Codefy\Framework\Helpers\trans_html;

$this->parent('framework::backend/layouts/admin-layout');
$this->block('backend', function ($params) {
Registry::getInstance()->{'set'}('screen_parent', 'sites');
Registry::getInstance()->{'set'}('screen_child', 'sites');
?>

    <script src="static/assets/js/url_slug.js" type="text/javascript"></script>
    <script>
        $(function(){
            $('#site_name').keyup(function() {
                $('#site_slug').val(url_slug($(this).val()));
            });
        });
    </script>

    <!-- form start -->
    <form name="form" method="post" data-toggle="validator" action="<?= admin_url('site/'); ?>" autocomplete="off">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="box box-solid">
                <div class="box-header with-border">
                    <i class="fa fa-thumb-tack"></i>
                    <h3 class="box-title"><?= trans_html(string: 'Sites'); ?></h3>

                    <div class="pull-right">
                        <input type="hidden" id="site_slug" name="slug" value="<?= $params['request']->getParsedBody()['slug'] ?? ''; ?>" />
                        <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> <?= trans_html(string: 'Save'); ?></button>
                    </div>
                </div>
            </div>

            <!-- Main content -->
            <section class="content">

                <?php Action::getInstance()->doAction('admin_notices'); ?>

                <?= Devflow::$PHP->flash->display(); ?>

                <div class="row">
                    <!-- left column -->
                    <div class="col-md-4">
                        <!-- general form elements -->
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= trans_html(string: 'Add New Site'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="form-group">
                                    <label><?= trans_html(string: 'Subdomain'); ?></label>
                                    <input type="text" class="form-control input-lg" name="subdomain" value="<?= $params['request']->getParsedBody()['subdomain'] ?? ''; ?>" required/>.<?= $params['request']->getServerParams()['HTTP_HOST']; ?>
                                </div>
                                <div class="form-group">
                                    <label><?= trans_html(string: 'Site Name'); ?></label>
                                    <input type="text" id="site_name" class="form-control" name="name" value="<?= $params['request']->getParsedBody()['name'] ?? ''; ?>" required/>
                                </div>
                                <div class="form-group">
                                    <label><?= trans_html(string: 'Path'); ?> <a href="#path" data-toggle="modal"><span class="badge"><i class="fa fa-question"></i></span></a></label>
                                    <input type="text" class="form-control" name="path" value="/" required/>
                                </div>
                                <div class="form-group">
                                    <label><?= trans_html(string: 'Administrator'); ?></label>
                                    <select class="form-control select2" name="owner" style="width: 100%;" required>
                                        <option>&nbsp;</option>
                                        <?php get_users_dropdown_list($params['request']->getParsedBody()['owner'] ?? ''); ?>
                                    </select>
                                </div>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.left column -->

                    <!-- right column -->
                    <div class="col-md-8">
                        <!-- general form elements -->
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"><?= trans_html(string: 'Sites'); ?></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <table id="example1" class="table table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th class="text-center"><?= trans_html(string: 'URL'); ?></th>
                                        <th class="text-center"><?= trans_html(string: 'Name'); ?></th>
                                        <th class="text-center"><?= trans_html(string: 'Admin'); ?></th>
                                        <th class="text-center"><?= trans_html(string: 'Status'); ?></th>
                                        <th class="text-center"><?= trans_html(string: 'Action'); ?></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($params['sites'] as $site) : ?>
                                        <tr class="gradeX">
                                            <td class="text-center"><a href="//<?= $site['domain']; ?><?= $site['path']; ?>" target="new"><?= $site['domain']; ?></a></td>
                                            <td class="text-center"><?= $site['name']; ?></td>
                                            <td class="text-center"><?= get_name($site['owner']); ?></td>
                                            <td class="text-center">
                                                <span class="label <?= cms_site_status_label($site['status']); ?>" style="font-size:1em;font-weight: bold;">
                                                    <?= ucfirst($site['status']); ?>
                                                </span>
                                            </td>
                                            <td class="text-center">
                                                <button type="button"<?= ae('update:sites');?> class="btn btn-success" onclick="window.location = '<?= admin_url('site/' . $site['id'] . '/'); ?>'"><i class="fa fa-pencil-alt"></i></button>
                                                <?php if ($site['domain'] <> config()->string('cms.main_site_url') || $site['key'] <> config()->string(sprintf('database.connections.%s.prefix', $params['connection']))) : ?>
                                                    <button type="button"<?= ae('delete:sites'); ?> class="btn bg-red" data-toggle="modal" data-target="#delete-<?= $site['id']; ?>"><i class="fa fa-trash"></i></button>
                                                <?php endif; ?>
                                                <div class="modal" id="delete-<?=$site['id'];?>">
                                                    <div class="modal-dialog">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span></button>
                                                                <h4 class="modal-title"><?=$site['domain'];?></h4>
                                                            </div>
                                                            <div class="modal-body">
                                                                <p><?= trans_html(string: "Are you sure you want to delete this site and all it's content"); ?></p>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-default pull-left" data-dismiss="modal"><?= trans_html(string: 'Close'); ?></button>
                                                                <button type="button" class="btn btn-primary" onclick="window.location = '<?= admin_url('site/' . $site['id'] . '/d/'); ?>'"><?= trans_html(string: 'Confirm'); ?></button>
                                                            </div>
                                                        </div>
                                                        <!-- /.modal-content -->
                                                    </div>
                                                    <!-- /.modal-dialog -->
                                                </div>
                                                <!-- /.modal -->
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th class="text-center"><?= trans_html(string: 'URL'); ?></th>
                                        <th class="text-center"><?= trans_html(string: 'Name'); ?></th>
                                        <th class="text-center"><?= trans_html(string: 'Admin'); ?></th>
                                        <th class="text-center"><?= trans_html(string: 'Status'); ?></th>
                                        <th class="text-center"><?= trans_html(string: 'Action'); ?></th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box-primary -->
                    </div>
                    <!-- /.right column -->

                </div>
                <!--/.row -->
            </section>
            <!-- /.Main content -->

            <!-- modal -->
            <div class="modal" id="path">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title"><?= trans_html(string: 'Site Path'); ?></h4>
                        </div>
                        <div class="modal-body">
                            <p><?= trans_html(string: "Based on your setup and where you installed the CMS, the system will figure out the correct path."); ?></p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default pull-left" data-dismiss="modal"><?= trans_html(string: 'Close'); ?></button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->

        </div>
    </form>
    <!-- /.Content Wrapper. Contains page content -->
<?php }); ?>
